// ================= v6 living ecosystem patch =================
const JT6={ver:6};
const JOURNAL_DEF={
 firstCatch:['First successful hunt','A jumper completed a stalk and captured live prey.'],
 ambush:['Ambush from cover','A jumper used cover or elevation to approach prey.'],
 drink:['Drank a droplet','A jumper found and drank fresh water.'],
 molt:['Successful molt','A jumper sealed into a retreat and emerged one stage larger.'],
 retreat:['Silk retreat','A jumper reinforced a sleeping or molting hammock.'],
 silk:['Safety silk','A visible dragline or anchor was left behind.'],
 investigate:['Curious inspection','A jumper investigated newly placed habitat decor.'],
 threat:['Territorial display','Two jumpers noticed one another and one displayed or retreated.'],
 cannibal:['Cannibalistic hunt','One jumper successfully hunted another jumper.'],
 tinyMiss:['Tiny jumper escape','A committed pounce at a tiny jumper missed.'],
 tinyCatch:['Tiny jumper capture','A committed pounce at a tiny jumper connected.'],
 softMolt:['Fresh-molt vulnerability','A freshly molted jumper was observed while still soft and pale.']
};
function recordJournal(id){if(!JOURNAL_DEF[id])return;G.journal=G.journal||{};if(!G.journal[id]){G.journal[id]={t:G.clock,n:1};toast('📓 Journal: '+JOURNAL_DEF[id][0]);}else G.journal[id].n=(G.journal[id].n||0)+1;}
function renderJournal(){const b=$('journalBody');if(!b)return;G.journal=G.journal||{};let html='';for(const id of Object.keys(JOURNAL_DEF)){const d=JOURNAL_DEF[id],u=G.journal[id];html+=`<div style="padding:9px 10px;margin:7px 0;border:1px solid ${u?'#8a5a35':'#b9a98b'};border-radius:6px;background:${u?'rgba(255,255,255,.28)':'rgba(90,70,45,.08)'}"><b>${u?'✓ ':'? '}${d[0]}</b><div style="font-size:12px;margin-top:3px;color:#6a4a2a">${u?d[1]:'Keep observing the terrarium to discover this behavior.'}</div>${u&&u.n>1?`<small>Observed ${u.n} times</small>`:''}</div>`;}b.innerHTML=html||'No observations yet.';}
$('journalBtn').onclick=()=>{renderJournal();$('journalModal').style.display='flex';};

const _v5MakeTank=makeTank;
makeTank=function(i){const t=_v5MakeTank(i);t.silk=[];t.humidity=0.38;t.age=0;t.novelty=null;return t;};
const _v5AddDecor=addDecor;
addDecor=function(t,type,x,z,rot=0,seed){const it=_v5AddDecor(t,type,x,z,rot,seed);if(!JT6.loading)t.novelty={id:it.id,t:G.clock};return it;};

function cloneSurf(s){return s?Object.assign({},s):S_FLOOR;}
function memSpot(e){return {surf:cloneSurf(e.surf),pt:vc(e.pos)};}
function targetProfile(p){if(p&&p.kind==='spider'){return {one:p.name||'jumper',name:p.name||'jumper',food:Math.max(18,spSize(p)*1.7),value:0,walk:16+spSize(p)*0.9,sense:92,sens:1.15,reflex:0.75,flyer:false,wall:true,strong:true,struggle:4+spSize(p)*0.22,danger:0.9,smart:true,size:spSize(p)};}return p&&PREY[p.type];}
function targetName(p){const q=targetProfile(p);return q?q.one:'target';}
function targetSize(p){return p&&p.kind==='spider'?spSize(p):(p?p.size:0);}
function targetValid(t,s,p){if(!p||p===s)return false;if(p.kind==='spider')return t.spiders.includes(p)&&!p._gone&&!p.owner;return t.prey.includes(p)&&!p.dead&&!p.owner&&!p.buried&&PREY[p.type]?.huntable!==false;}
function spiderPower(s){return (s.stage||1)*100+spSize(s)*6+(s.softT>0?-40:0);}
function stronger(a,b){return spiderPower(a)>spiderPower(b)+0.001;}
function addSilk(t,a,b,kind='drag',alpha=0.24){if(!t.silk)t.silk=[];if(vdist(a,b)<2)return;t.silk.push({a:vc(a),b:vc(b),kind,alpha,age:0});if(t.silk.length>140)t.silk.splice(0,t.silk.length-140);recordJournal('silk');}
function personalityLabel(s){const p=s.persona||{};const out=[];if((s.obsPts||0)>=2)out.push(p.curiosity>.66?'curious':p.curiosity<.34?'reserved':'observant');if((s.obsPts||0)>=4)out.push(p.activity>.66?'busy':p.activity<.34?'unhurried':'steady');if((s.obsPts||0)>=6)out.push(p.territorial>.66?'territorial':p.cannibal>.7?'opportunistic hunter':s.tr.patience>.65?'patient':'adaptable');return out.length?out.join(' • '):'still learning…';}

const _v5NewSpider=newSpider;
newSpider=function(spid,t){const s=_v5NewSpider(spid,t),S=SPEC[spid],r=rng((s.seed^0x6a09e667)>>>0);s.persona={curiosity:clamp(.25+S.st.bold*.45+r()*.3,0,1),activity:clamp(.25+(1-S.st.patience)*.35+r()*.4,0,1),territorial:clamp(.12+S.st.bold*.45+r()*.38,0,1),cannibal:clamp(.1+S.st.bold*.38+r()*.42,0,1),twitch:clamp((1-S.st.patience)*.65+r()*.25,0,1),routine:clamp(S.st.patience*.55+r()*.4,0,1),humPref:clamp(.34+S.st.stealth*.18+(spid==='otiosus'||spid==='lysso'||spid==='emerald'?0.15:0)+r()*.08,0.28,.76)};s.mem={rest:null,water:null,hunt:[],decor:{}};s.attn=null;s.attnT=0;s.obsPts=0;s.softT=0;s.predAlert=0;s._silkAnchor=vc(s.pos);s._silkDist=0;s.size=spSize(s);return s;};
const _v5NewPrey=newPrey;
newPrey=function(type,t,pos){const p=_v5NewPrey(type,t,pos);p.scanClock=rr(.4,1.5);p.personality=rr(.75,1.25);return p;};
nearestSpider=function(t,p){let b=null,bd=1e9;for(const s of t.spiders){if(s.owner||s._gone)continue;const d=vdist(s.pos,p.pos);if(d<bd){bd=d;b=s;}}return [b,bd];};

// Pause briefly before committing to a climb/descend so feet do not appear to transfer through empty space.
followRoute=function(t,e,spd,dt,lockFace){if(!e.route||!e.route.length)return true;const seg=e.route[0];
 if(seg.hop){if(!e.jump)startJump(e,seg.pt,seg.surf,Math.max(5,vdist(e.pos,seg.pt)*0.25),spd*4.5);return false;}
 if(e.kind==='spider'&&seg.climb&&!sameSurf(e.surf,seg.surf)){const key=(seg.surf.id||'')+':'+Math.round(seg.pt.x)+':'+Math.round(seg.pt.z);if(e._probeKey!==key){e._probeKey=key;e._probeT=0.18+0.12*(e.persona?1-e.persona.activity:0.5);}if(e._probeT>0){e._probeT-=dt;faceToward(e,seg.pt,7,dt);e.spd=0;return false;}e._probeKey='';if(!e.mem)e.mem={};recordJournal('silk');}
 if(!sameSurf(e.surf,seg.surf))e.surf=seg.surf;const d=vsub(seg.pt,e.pos),L=vlen(d),step=spd*dt*(seg.climb?0.64:1);
 if(L<=step+0.01){e.pos=vc(seg.pt);if(e.surf.t==='plat'){const pd=platById(t,e.surf.id);if(pd)e.pos.y=platTopY(pd,e.pos.x,e.pos.z);}e.route.shift();if(!e.route.length){if(seg.surf.t!=='climb')clampSurf(t,e);return true;}return false;}
 const nd=vmul(d,1/L);e.pos=vadd(e.pos,vmul(nd,step));if(e.surf.t==='plat'){const pd=platById(t,e.surf.id);if(pd)e.pos.y=platTopY(pd,e.pos.x,e.pos.z);}e.moved+=step;if(!lockFace||seg.climb||e.surf.t==='wall'){if(e.kind==='spider'&&!seg.climb&&(e.surf.t==='floor'||e.surf.t==='plat'))turnFaceFlat(e,nd,8,dt);else e.face=vnorm(d);}return false;};

function scanCannibal(t,s){if(s.sat>76||s.stage<2)return null;let best=null,bs=-1e9;for(const o of t.spiders){if(o===s||o.owner||o._gone||(s.ignore[o.id]||0)>G.clock)continue;const d=vdist(s.pos,o.pos);if(d>110||!LOS(t,eyePos(s),o.pos))continue;const adv=spiderPower(s)-spiderPower(o);if(adv<-8)continue;const vulnerable=o.softT>0||o.state==='molt'||o.state==='sleep';let urge=(1-s.sat/100)*1.2+(s.persona?.cannibal||.4)*.8+(s.persona?.territorial||.3)*.2+clamp(adv/160,0,.8)+(vulnerable?.45:0);if(Math.abs(adv)<15)urge*=.45;if(urge<.63)continue;const sc=urge*2-d/120+rand()*.15;if(sc>bs){bs=sc;best=o;}}return best;}
function nearbyRival(t,s){let b=null,bd=1e9;for(const o of t.spiders){if(o===s||o.owner)continue;const d=vdist(s.pos,o.pos);if(d<bd){bd=d;b=o;}}return bd<34?b:null;}

scanPrey=(function(old){return function(t,s){const prey=old(t,s);if(prey)return prey;return scanCannibal(t,s);};})(scanPrey);

planAmbush=function(t,s,p){const R=jumpRange(s),sz=spSize(s),P_=targetProfile(p),cands=[],pp=p.pos;
 for(let i=0;i<14;i++){const a=i/14*Math.PI*2+rand()*0.3,d=R*rr(.4,.8),q=v3(pp.x+Math.cos(a)*d,0,pp.z+Math.sin(a)*d);if(q.x<3||q.x>TW-3||q.z<3||q.z>TD-3)continue;const g=groundAt(t,q.x,q.z);if(g.p){q.y=g.h;cands.push({surf:{t:'plat',id:g.p.id},pt:q});}else cands.push({surf:S_FLOOR,pt:q});}
 for(const d of plats(t)){const q=v3(clamp(pp.x,d.x0+1,d.x1-1),d.h,clamp(pp.z,d.z0+1,d.z1-1));cands.push({surf:{t:'plat',id:d.id},pt:q});for(let i=0;i<3;i++)cands.push({surf:{t:'plat',id:d.id},pt:v3(rr(d.x0+1,d.x1-1),d.h,rr(d.z0+1,d.z1-1))});}
 for(const w of ['z0','x0','xW','zD'])for(const dy of [6,14,26])cands.push({surf:{t:'wall',w},pt:wallClamp(w,v3(pp.x+rr(-12,12),pp.y+dy,pp.z+rr(-12,12)))});
 const pf=p.face||v3(1,0,0);let best=null,bs=-1e9;for(const c of cands){const d=vdist(c.pt,pp);if(d>R*.92||d<sz*1.3)continue;if(!LOS(t,v3(c.pt.x,c.pt.y+sz*.3,c.pt.z),pp))continue;const segs=route(t,s,c.surf,c.pt),L=routeLen(s,segs);let sc=-L*.12*(1.25-s.tr.patience);const elev=c.pt.y-pp.y;if(elev>3)sc+=Math.min(elev,30)*.55*(.4+s.tr.tactic);const dir=vnorm(vsub(c.pt,pp));sc+=-vdot(pf,dir)*12*(.3+s.tr.stealth)*(P_.flyer?.3:1);if(inCover(t,c.pt.x,c.pt.z,c.pt.y))sc+=7*s.tr.stealth;for(let i=1;i<segs.length;i++)if(vdist(segs[i].pt,pp)<P_.sense*.55)sc-=6*(.5+s.tr.tactic);sc-=Math.abs(d-R*.6)*.2;sc+=rand()*3;if(sc>bs){bs=sc;best={surf:c.surf,pt:c.pt,segs,L};}}return best;};

giveUp=function(s,msg){if(s.hunt&&s.hunt.prey){const p=s.hunt.prey;s.ignore[p.id]=G.clock+12;if(p.kind==='spider'&&p._huntedBy===s)p._huntedBy=null;}s.hunt=null;s.route=null;setSt(s,'look',msg||'Lost interest');};
startHunt=function(t,s,p){const a=planAmbush(t,s,p),same=s.hunt&&s.hunt.prey===p,keep={replans:same?(s.hunt.replans||0):0,t0:same&&s.hunt.t0?s.hunt.t0:G.clock};if(p.kind==='spider')p._huntedBy=s;if(!a){s.hunt={prey:p,amb:null,plan:vc(p.pos),lost:0,burst:0,creep:true,cool:2,...keep};s.route=route(t,s,p.surf.t==='perch'||p.surf.t==='air'?S_FLOOR:p.surf,p.surf.t==='perch'?v3(p.pos.x,0,p.pos.z):p.pos);}else{s.hunt={prey:p,amb:a,plan:vc(p.pos),lost:0,burst:0,creep:true,cool:2.5,...keep};s.route=a.segs;}const nm=targetName(p),detour=a&&a.L>vdist(s.pos,p.pos)*1.4,high=a&&a.pt.y>p.pos.y+4;if(detour||high)recordJournal('ambush');s.obsPts=(s.obsPts||0)+.35;setSt(s,'stalk',detour?`Taking the long way around to ${nm}`:high?`Climbing for a high angle on ${nm}`:`Stalking ${nm}`);};
preyWatching=function(p,s){if(p.kind!=='spider'&&p.type==='mealworm')return false;if(p.kind==='spider'&&(p.state==='sleep'||p.state==='molt'||p.owner))return false;const d=vsub(s.pos,p.pos);d.y=0;if(vlen(d)<.01)return true;const pf=v3(p.face.x,0,p.face.z);if(vlen(pf)<.01)return false;return Math.acos(clamp(vdot(vnorm(pf),vnorm(d)),-1,1))<=25*Math.PI/180;};
holdPrey=function(s){const p=s.hunt&&s.hunt.prey;if(!p||p.owner!==s)return;const sz=spSize(s),f=s.face;p.pos=vadd(s.pos,vmul(f,sz*.55));if(s.surf.t==='wall')p.pos=vadd(p.pos,vmul(wallNormal(s.surf.w),.5));else p.pos.y=s.pos.y+sz*.15;p.surf=s.surf;p.face=vmul(f,-1);};
catchPrey=function(t,s,p){const P_=targetProfile(p),nm=targetName(p);p.owner=s;p.state='caught';p.jump=null;p.route=null;s.jump=null;s.drag=null;if(p.kind==='spider'){p.size=spSize(p);p._huntedBy=null;if(G.sel===p)G.sel=s;recordJournal('cannibal');}else if(p.type==='sjumper')recordJournal('tinyCatch');addFx(t,'bite',p.pos);addFx(t,'text',vadd(p.pos,v3(0,8,0)),p.kind==='spider'?'CANNIBAL!':'GOT IT!');SFX.catch();s.hunt.subT=P_.struggle;const okSurf=p.surf.t==='floor'||p.surf.t==='plat'||p.surf.t==='wall';if(okSurf){s.surf=p.surf;s.pos=vsub(p.pos,vmul(s.face,spSize(s)*.5));clampSurf(t,s);setSt(s,'subdue',p.kind==='spider'?`Overpowered ${nm}`:`Got the ${nm}! Holding on tight...`);}else{s.surf={t:'air'};s.vel=v3();s.after='subdue';setSt(s,'fall',`Snatched ${nm} mid-air!`);}};

function spiderEscape(t,s,thr){if(!thr)return;const away=vnorm(v3(s.pos.x-thr.pos.x,0,s.pos.z-thr.pos.z));if((s.surf.t==='floor'||s.surf.t==='plat')&&jumpRange(s)>20){const q=v3(clamp(s.pos.x+away.x*rr(22,36),3,TW-3),0,clamp(s.pos.z+away.z*rr(22,36),3,TD-3)),g=groundAt(t,q.x,q.z);q.y=g.h;startJump(s,q,g.p?{t:'plat',id:g.p.id}:S_FLOOR,6+spSize(s)*.25,80+s.tr.jump*60);setSt(s,'escape','Leaping away from the larger jumper');}else{s.route=route(t,s,S_FLOOR,v3(clamp(s.pos.x+away.x*35,3,TW-3),0,clamp(s.pos.z+away.z*35,3,TD-3)));setSt(s,'escape','Retreating from another jumper');}}

updSpider=function(t,s,dt){s.size=spSize(s);if(s.owner){s.spd=0;s.anim+=dt*.35;return;}const sz=s.size;s.anim+=dt;s.st+=dt;const prev=vc(s.pos);s.moved=0;s._stalkFrozen=false;if(s.softT>0){s.softT=Math.max(0,s.softT-dt);if(s.softT>0&&rand()<dt*.03)recordJournal('softMolt');}
 if(s.state!=='sleep'&&s.state!=='molt'&&s.state!=='premolt')s.sat=Math.max(0,s.sat-dt*.2);s.thirst=Math.min(1,s.thirst+dt/420);s.attnT=Math.max(0,(s.attnT||0)-dt);s.predAlert=Math.max(0,(s.predAlert||0)-dt*.08);
 const hum=t.humidity??.38,comfort=1-clamp(Math.abs(hum-(s.persona?.humPref||.45))/.55,0,.35),walk=(16+sz*.9)*(.86+.22*(s.persona?.activity||.5))*comfort,night=isNight(),idle=['wander','look','rest','watch','bask','anchor','investigate','inspect','display'].includes(s.state);
 if(typeof awarenessV7==='function'&&['notice','stalk','distract','crouch'].includes(s.state))awarenessV7(t,s,dt,walk);
 const hunter=s._huntedBy;if(hunter&&!hunter.owner&&t.spiders.includes(hunter)&&vdist(s.pos,hunter.pos)<95&&LOS(t,eyePos(s),hunter.pos)){const sees=preyWatching(s,hunter),motion=hunter.spd>1?1:.25;s.predAlert=clamp(s.predAlert+dt*(sees?.75:.18)*motion*(1+vdist(s.pos,hunter.pos)<35),0,1);if(s.predAlert>.64&&idle){s.route=null;s.attn={kind:'spider',id:hunter.id,pos:vc(hunter.pos)};s.obsPts=(s.obsPts||0)+.15;recordJournal('threat');setSt(s,'threat',`Watching ${hunter.name} carefully`);}}
 if(idle){const rival=nearbyRival(t,s);if(rival&&!rival._huntedBy&&rand()<dt*.08*(s.persona?.territorial||.4)){s.rival=rival;s.route=null;setSt(s,'display',`Posturing at ${rival.name}`);recordJournal('threat');}}
 if(idle&&t.novelty&&G.clock-t.novelty.t<28&&(s.persona?.curiosity||.5)>.34&&!s.mem?.decor?.[t.novelty.id]){const d=platById(t,t.novelty.id);if(d&&vdist(s.pos,v3(d.x,0,d.z))<120&&rand()<dt*.35*(s.persona.curiosity||.5)){const m=2.5,q=v3(clamp(d.x+(s.pos.x<d.x?-1:1)*(d.w/2+m),2,TW-2),0,clamp(d.z+(s.pos.z<d.z?-1:1)*(d.d/2+m),2,TD-2));s.inspectId=d.id;s.route=route(t,s,S_FLOOR,q);setSt(s,'investigate',`Going to inspect the new ${DECOR[d.type].name.toLowerCase()}`);}}
 if(idle&&night){if(!s.retreat)pickRetreat(t,s);s.route=route(t,s,s.retreat.surf,s.retreat.pt);setSt(s,'toRetreat','Heading to its silk retreat for the night');}
 if(idle&&!night&&s.meals>=3+s.stage&&s.stage<6&&s.sat>55){if(!s.retreat)pickRetreat(t,s);s.route=route(t,s,s.retreat.surf,s.retreat.pt);setSt(s,'toMolt','Feeling tight... sealing into a molt retreat');}
 if(idle&&!night&&t.drops.length&&s.thirst>.45&&s.state!=='watch'){let b=null,bd=1e9;for(const d of t.drops){if(d.surf.t==='perch')continue;const dd=vdist(d.pos,s.pos);if(dd<bd){bd=dd;b=d;}}if(b){s.route=route(t,s,b.surf,b.pos);s.dropT=b;setSt(s,'toDrink','Thirsty - heading for a water droplet');}}
 if(idle&&!night&&s.sat<82&&s.state!=='watch'){s.scanT-=dt;if(s.scanT<=0){s.scanT=.22+(.18*(1-(s.persona?.activity||.5)));const p=scanPrey(t,s);if(p){s.hunt={prey:p};s.route=null;s.attn={kind:p.kind,id:p.id,pos:vc(p.pos)};setSt(s,'notice',p.kind==='spider'?`Noticed ${p.name} as possible prey`:`Spotted a ${targetName(p)}!`);}}}
 if(idle&&G.cur===t.id&&G.mouseScr&&s.state!=='watch'&&!s.jump&&s.surf.t!=='climb'){const sp=Pv(s.pos);if(Math.hypot(sp[0]-G.mouseScr[0],sp[1]-G.mouseScr[1])<45*(cam.k/RS/2)*RS+20*RS){s.route=null;s.attn={kind:'viewer',pos:G.mouse?vc(G.mouse):vc(s.pos)};setSt(s,'watch','Watching you curiously 👀');}}
 if(s.jump&&s.state!=='pounce'){if(stepJump(s,dt)){const j=s.jump;s.surf=j.surfTo;s.pos=vc(j.to);s.jump=null;if(s.route&&s.route.length)s.route.shift();clampSurf(t,s);addSilk(t,j.anchor,s.pos,'jump',.32);addFx(t,'dust',s.pos);}}
 else switch(s.state){
  case 'wander':{if(!s.route){let d;if(s.mem?.rest&&rand()<(s.persona?.routine||.4)*.24)d={surf:cloneSurf(s.mem.rest.surf),pt:vc(s.mem.rest.pt)};else if(s.mem?.hunt?.length&&s.sat<60&&rand()<.18)d={surf:cloneSurf(s.mem.hunt[0].surf),pt:vc(s.mem.hunt[0].pt)};else{let tries=0;do{d=randSurfPoint(t,{plat:.4,wall:.35});tries++;}while(tries<6&&t.spiders.some(o=>o!==s&&!o.owner&&vdist(o.pos,d.pt)<35));}s.route=route(t,s,d.surf,d.pt,jumpRange(s)*.55);}if(s.pauseT>0){s.pauseT-=dt;break;}if(rand()<dt*(.18+.34*(1-(s.persona?.activity||.5))))s.pauseT=rr(.25,1.5);if(followRoute(t,s,walk,dt)){s.route=null;s.lookA=Math.atan2(s.face.z,s.face.x);const r=rand(),st=r<.15?'groom':r<.28?'rest':r<.38?'anchor':r<.48?'bask':'look';setSt(s,st,st==='anchor'?'Attaching a tiny silk anchor':st==='bask'?'Settling into a comfortable lookout':'Surveying the tank');}if(s.st>30){s.route=null;setSt(s,'look');}break;}
  case 'look':{if(s.surf.t!=='wall'&&s.surf.t!=='climb'){const a=s.lookA+Math.sin(s.st*1.3)*.9*(Math.sin(s.st*.37)>0?1:-1);turnFaceFlat(s,v3(Math.cos(a),0,Math.sin(a)),2.2,dt);}if(s.st>(s.lookT||(s.lookT=rr(2,5)))){s.lookT=0;setSt(s,'wander','Exploring');}break;}
  case 'watch':{const vd=viewDir();let tgt=vadd(s.pos,vmul(vd,30));if(G.mouse)tgt=vadd(tgt,vmul(vsub(G.mouse,s.pos),.4));s.attn={kind:'viewer',pos:vc(tgt)};if(s.surf.t!=='wall'&&s.st>.55)faceToward(s,tgt,2.4,dt);const sp=Pv(s.pos),near=G.mouseScr&&G.cur===t.id&&Math.hypot(sp[0]-G.mouseScr[0],sp[1]-G.mouseScr[1])<55*(cam.k/RS/2)*RS+30*RS;if(near)s.st=Math.min(s.st,.1);if(s.st>1.5)setSt(s,'look','Back to exploring');break;}
  case 'groom':if(s.st>2.5){s.obsPts+=.08;setSt(s,'look','Cleaning its eyes and palps');}break;
  case 'rest':if(!s.mem.rest||rand()<.2)s.mem.rest=memSpot(s);if(s.st>(s.restT||(s.restT=rr(3,8)))){s.restT=0;setSt(s,'look','Rested and alert');}break;
  case 'bask':{if(!s.mem.rest)s.mem.rest=memSpot(s);if(s.st>rr(3,6))setSt(s,'look','Comfortably warmed up');break;}
  case 'anchor':{if(s.st<dt*1.5)addSilk(t,vadd(s.pos,v3(-1,0,-1)),vadd(s.pos,v3(1.5,0,1.5)),'anchor',.38);if(s.st>1.4){s.obsPts+=.1;setSt(s,'look','Silk anchor secured');}break;}
  case 'investigate':{if(followRoute(t,s,walk*.72,dt)){s.route=null;setSt(s,'inspect','Touching the new object with its front legs');}break;}
  case 'inspect':{const d=platById(t,s.inspectId);if(d)faceToward(s,v3(d.x,s.pos.y,d.z),3,dt);if(s.st>2.2){s.mem.decor[s.inspectId]=1;s.obsPts+=.7;recordJournal('investigate');setSt(s,'look','Finished inspecting the new addition');}break;}
  case 'display':{const r=s.rival;if(!r||r.owner||vdist(s.pos,r.pos)>45){s.rival=null;setSt(s,'look');break;}faceToward(s,r.pos,5,dt);if(s.st>1.2){if(stronger(r,s))spiderEscape(t,s,r);else {s.rival=null;setSt(s,'look','Holding its ground');}}break;}
  case 'threat':{const h=s._huntedBy;if(!h||h.owner||!t.spiders.includes(h)){s._huntedBy=null;setSt(s,'look');break;}faceToward(s,h.pos,7,dt);if(s.st>.65+(s.tr.patience*.35))spiderEscape(t,s,h);break;}
  case 'escape':{if(s.jump)break;if(s.route&&followRoute(t,s,walk*1.2,dt)){s.route=null;s.predAlert=.2;setSt(s,'look','Keeping its distance');}if(s.st>4&&!s.route)setSt(s,'look');break;}
  case 'mistReact':{if(s.st<.7&&s.surf.t!=='wall')turnFaceFlat(s,v3(-s.face.x,0,-s.face.z),2,dt);if(s.st>1.2)setSt(s,'groom','Wiping moisture from its face');break;}
  case 'distract':{const q=s._distractObj,orig=s._resumeTarget;if(q&&targetValid(t,s,q)){s.attn={kind:q.kind,id:q.id,pos:vc(q.pos)};faceToward(s,q.pos,4.5,dt);}if(s.st>(s._distractDur||.75)){s._distractObj=null;s._distractDur=0;s._resumeTarget=null;if(orig&&targetValid(t,s,orig)){s.hunt={prey:orig};startHunt(t,s,orig);s.mood=`Reacquired ${targetName(orig)}`;}else setSt(s,'look','The distraction passed');}break;}
  case 'notice':{const p=s.hunt&&s.hunt.prey;if(!targetValid(t,s,p)){giveUp(s);break;}s.attn={kind:p.kind,id:p.id,pos:vc(p.pos)};faceToward(s,p.pos,6,dt);if(s.st>.5+s.tr.patience*.9){const P_=targetProfile(p),nm=targetName(p);if(p.kind==='spider'){if(!stronger(s,p)&&!p.softT){s.ignore[p.id]=G.clock+18;s.hunt=null;setSt(s,'display',`Sizing up ${nm} instead of attacking`);s.rival=p;recordJournal('threat');}else startHunt(t,s,p);}else if(p.size>sz*(1.15+s.tr.bold*.9)||(P_.danger&&rand()>s.tr.bold*.9+.15)){s.ignore[p.id]=G.clock+25;s.hunt=null;setSt(s,'look',`Sized up the ${nm}... too risky`);}else startHunt(t,s,p);}break;}
  case 'stalk':{const h=s.hunt,p=h&&h.prey;if(!targetValid(t,s,p)){giveUp(s,'Target got away');break;}const P_=targetProfile(p),R=jumpRange(s);h.cool-=dt;if(G.clock-h.t0>45+s.tr.patience*38){giveUp(s,'Giving the hunt a rest');s.ignore[p.id]=G.clock+30;break;}const d=vdist(s.pos,p.pos),vis=LOS(t,eyePos(s),p.pos)&&d<165,nm=targetName(p);s.attn={kind:p.kind,id:p.id,pos:vc(p.pos)};h.liveBearing=Math.atan2(p.pos.z-s.pos.z,p.pos.x-s.pos.x);if(vis)h.lost=0;else if((h.lost+=dt)>9){giveUp(s,`Lost track of ${nm}`);break;}const watched=vis&&preyWatching(p,s),closeCommit=vis&&d<=pounceCommitRange(s)&&!s.jump&&s.surf.t!=='climb'&&p.surf.t!=='air';if(watched&&closeCommit){s._stalkFrozen=false;s.route=null;h.forceCommit=true;h.aimStart=G.clock;h.aimPos=vc(p.pos);h.lastSeen=vc(p.pos);setSt(s,'crouch',`${nm} is too close — committing to the pounce`);break;}if(watched){s._stalkFrozen=true;s.route=s.route||[];faceToward(s,p.pos,4.2,dt);h.lastSeen=vc(p.pos);s.mood=`Frozen – ${nm} is looking right at it`;break;}if(p.surf.t==='air'&&p.kind!=='spider'){faceToward(s,p.pos,5.2,dt);h.air=(h.air||0)+dt;s.mood=`Tracking the flying ${nm}...`;if(h.air>6)giveUp(s,`${nm} flew off`);break;}h.air=0;h.liveT=(h.liveT||0)-dt;const movedFromPlan=vdist(p.pos,h.plan||p.pos);if(h.liveT<=0){h.liveT=.16;const near=d<Math.max(R*2.4,56);if(near&&(p.surf.t==='floor'||p.surf.t==='plat'||p.kind==='spider')){const away=vnorm(v3(s.pos.x-p.pos.x,0,s.pos.z-p.pos.z)),stand=Math.max(R*.58,sz*1.35),q=v3(clamp(p.pos.x+away.x*stand,2,TW-2),p.pos.y,clamp(p.pos.z+away.z*stand,2,TD-2));let qs=p.surf;if(p.kind!=='spider'){const g=groundAt(t,q.x,q.z);q.y=g.h;qs=g.p?{t:'plat',id:g.p.id}:S_FLOOR;}s.route=route(t,s,qs,q,jumpRange(s)*.38);h.plan=vc(p.pos);}else if(movedFromPlan>9&&h.cool<=0){h.replans++;if(h.replans>7){giveUp(s,'Too slippery, giving up');break;}startHunt(t,s,p);s.mood=`Following the prey's new line`;break;}}const farN=clamp((d-R*.78)/Math.max(1,R*2.2),0,1);h.burst-=dt;if(h.burst<=0){if(farN>.48){h.creep=true;h.burst=rr(.72,1.5);}else{h.creep=!h.creep;h.burst=h.creep?rr(.38,1.0):rr(.18,.72)*(.55+s.tr.patience);}}const crouchOK=vis&&d<R*1.03&&!s.jump&&s.surf.t!=='climb'&&p.surf.t!=='air',done=!s.route||!s.route.length;if(crouchOK&&(done||d<R*.64)){s.route=null;h.forceCommit=false;h.aimStart=G.clock;h.aimPos=vc(p.pos);setSt(s,'crouch','Lining up the jump... calculating');break;}if((h.creep||farN>.48)&&!done){if(s.surf.t==='wall')liveWallTrackV19(s,p);h.rearFactor=preyRearFactor(p,s);const stalk=stalkingSpeed(s,p,walk,d);followRoute(t,s,stalk,dt,false);}else if(vis&&s.surf.t!=='climb')faceToward(s,p.pos,4.6,dt);if(done&&!crouchOK&&s.st>1){h.replans++;if(h.replans>7){giveUp(s,'Could not find an angle');break;}startHunt(t,s,p);}break;}
  case 'crouch':{const h=s.hunt,p=h&&h.prey;if(!targetValid(t,s,p)){giveUp(s);break;}const P_=targetProfile(p),d=vdist(s.pos,p.pos),tiny=p.kind!=='spider'&&p.type==='sjumper';s.attn={kind:p.kind,id:p.id,pos:vc(p.pos)};faceToward(s,p.pos,9,dt);h.aimPos=vc(p.pos);const commit=h.forceCommit?(.16+s.tr.patience*.18):(.42+s.tr.patience*.72);if(!tiny&&p.surf.t==='air'&&s.st<commit*.65){s.mood='Holding the crouch - waiting for a landing';}if(!tiny&&d>jumpRange(s)*1.35&&s.st<commit){h.cool=0;startHunt(t,s,p);break;}if(s.st>commit||tiny&&s.st>.38){h.fixedOutcome=tiny?rand()<.5:null;h.launchAt=vc(p.pos);setSt(s,'pounce','POUNCE!');}break;}
  case 'pounce':{const h=s.hunt,p=h&&h.prey;if(!s.jump){if(!targetValid(t,s,p)){giveUp(s);break;}const d=vdist(s.pos,p.pos),spd=95+s.tr.jump*80,T=d/spd,lead=.3+s.tr.tactic*.6;let tg=vadd(p.pos,vmul(p.vel||v3(),T*lead*((p.spd||0)>1?1:0))),surfTo=p.surf;if(p.surf.t==='wall')tg=wallClamp(p.surf.w,tg);else if(p.surf.t==='floor'||p.surf.t==='plat'||p.kind==='spider'){const g=groundAt(t,tg.x,tg.z);tg.y=(p.kind==='spider'?p.pos.y:g.h);surfTo=p.kind==='spider'?p.surf:(g.p?{t:'plat',id:g.p.id}:S_FLOOR);tg.x=clamp(tg.x,2,TW-2);tg.z=clamp(tg.z,2,TD-2);}else surfTo=null;const from=s.surf;startJump(s,tg,surfTo,3+d*.2,spd);s.jump.fromSurf=from;s.drag={a:vc(s.pos)};addFx(t,'text',vadd(s.pos,v3(0,10,0)),'POUNCE!');SFX.pounce();if(p.kind!=='spider'&&p.type!=='sjumper')preyDodge(t,p,s);break;}
    if(p&&p.kind!=='spider'&&p.type==='sjumper'&&h.fixedOutcome&&targetValid(t,s,p)){const g=groundAt(t,p.pos.x,p.pos.z);s.jump.to=v3(p.pos.x,p.surf.t==='air'?p.pos.y:g.h,p.pos.z);s.jump.surfTo=p.surf.t==='air'?null:(g.p?{t:'plat',id:g.p.id}:p.surf);}
    const end=stepJump(s,dt),tiny=p&&p.kind!=='spider'&&p.type==='sjumper',hit=targetValid(t,s,p)&&vdist(s.pos,p.pos)<sz*.45+targetSize(p)*.5+1.5,allow=!tiny||h.fixedOutcome;if(hit&&allow){s.drag.b=null;catchPrey(t,s,p);break;}if(end&&tiny&&h.fixedOutcome&&targetValid(t,s,p)){s.pos=vc(p.pos);s.drag.b=null;catchPrey(t,s,p);break;}if(end){const j=s.jump;s.jump=null;if(p)s.ignore[p.id]=G.clock+2;if(tiny&&!h.fixedOutcome)recordJournal('tinyMiss');if(j.surfTo){s.surf=j.surfTo;s.pos=vc(j.to);clampSurf(t,s);addSilk(t,j.anchor,s.pos,'pounce',.42);s.drag=null;addFx(t,'dust',s.pos);s.hunt=null;setSt(s,'missed',p&&p.type==='sjumper'?'Tiny jumper escaped the pounce!':'Missed! Regrouping...');}else if(j.anchor.y>12){s.dg={a:j.anchor,surf:j.fromSurf,len:Math.min(vdist(j.anchor,s.pos),j.anchor.y-groundAt(t,s.pos.x,s.pos.z).h-3)};s.hunt=null;setSt(s,'dangle','Missed - dangling on its safety line!');}else{s.vel=v3();s.after='missed';s.hunt=null;s.drag=null;setSt(s,'fall','Missed!');}}break;}
  case 'dangle':{const g=s.dg,sw=Math.sin(s.st*3)*Math.max(0,4-s.st*1.5);if(s.st>1.6)g.len=Math.max(0,g.len-dt*14);s.pos=v3(g.a.x+sw,g.a.y-Math.max(0,g.len),g.a.z);s.face=v3(0,1,0);s.surf={t:'silk'};s.drag={a:g.a};if(s.st>1.6&&g.len<=.5){s.surf=g.surf;s.pos=vc(g.a);clampSurf(t,s);s.drag=null;s.face=v3(1,0,0);setSt(s,'missed','Climbed back up its dragline');}break;}
  case 'fall':{s.vel.y-=260*dt;s.pos=vadd(s.pos,vmul(s.vel,dt));const g=groundAt(t,s.pos.x,s.pos.z);if(s.pos.y<=g.h){s.pos.y=g.h;s.surf=g.p?{t:'plat',id:g.p.id}:S_FLOOR;clampSurf(t,s);s.drag=null;addFx(t,'dust',s.pos);s.face=vnorm(v3(s.face.x||1,0,s.face.z));setSt(s,s.after||'missed',s.after==='subdue'?s.mood:'Landed');}break;}
  case 'missed':if(s.st>1.3)setSt(s,'look','Watching carefully');break;
  case 'subdue':{const h=s.hunt,p=h&&h.prey;if(!p){giveUp(s);break;}const P_=targetProfile(p);h.subT-=dt;if(p.kind==='spider'){if(!stronger(s,p)){p.owner=null;p._huntedBy=null;s.hunt=null;spiderEscape(t,s,p);break;}}else if(P_.strong&&sz<p.size*.95&&rand()<dt*.07){p.owner=null;p.state='idle';p.alert=1;preyFlee(t,p,s);s.hunt=null;setSt(s,'missed',`The ${P_.one} kicked free!`);break;}if(h.subT<=0){if(p.kind!=='spider'){p.dead=true;G.catches++;s.catches++;G.coins+=P_.value;addFx(t,'text',vadd(s.pos,v3(0,12,0)),'+'+P_.value);toast(`${s.name} caught a ${P_.one}! +${P_.value} 🪙`);SFX.coin();checkUnlocks();recordJournal('firstCatch');}else{toast(`${s.name} overpowered ${p.name}.`);}s.obsPts+=1.2;s.mem.hunt.unshift(memSpot(s));s.mem.hunt=s.mem.hunt.slice(0,3);if(s.surf.t==='floor'){const sp=safeSpot(t,s);if(sp&&vdist(sp.pt,s.pos)<70){s.route=route(t,s,sp.surf,sp.pt);setSt(s,'carry','Carrying its meal somewhere safe');break;}}setSt(s,'feed','Feeding...');h.feedT=0;}break;}
  case 'carry':if(followRoute(t,s,walk*.55,dt)){setSt(s,'feed','Feeding...');s.hunt.feedT=0;}break;
  case 'feed':{const h=s.hunt,p=h&&h.prey;if(!p){giveUp(s);break;}const P_=targetProfile(p),dur=8+targetSize(p)*1.1;h.feedT+=dt;p.feed=Math.min(1,h.feedT/dur);s.sat=Math.min(100,s.sat+P_.food*dt/dur*clamp(14/sz,.7,2));if(h.feedT>=dur){if(p.kind==='spider'){p._gone=true;(t._removeSpiders||(t._removeSpiders=[])).push(p);const g=groundAt(t,s.pos.x,s.pos.z);t.husks.push({type:'spiderMeal',sp:p.sp,pos:v3(s.pos.x,g.h,s.pos.z),size:spSize(p),surf:s.surf,face:vc(p.face),seed:p.seed});}else{const ix=t.prey.indexOf(p);if(ix>=0)t.prey.splice(ix,1);const g=groundAt(t,p.pos.x,p.pos.z);t.husks.push({type:p.type,pos:v3(clamp(p.pos.x,2,TW-2),g.h,clamp(p.pos.z,2,TD-2)),size:p.size,seed:p.seed,face:p.face});s.meals++;}s.hunt=null;setSt(s,'groom','Finished eating - cleaning up');}break;}
  case 'toRetreat':case 'toMolt':case 'toDrink':{if(followRoute(t,s,walk,dt)){s.route=null;if(s.state==='toRetreat'){s.mem.rest=memSpot(s);recordJournal('retreat');setSt(s,'sleep','Sleeping in its silk retreat 💤');}else if(s.state==='toMolt'){recordJournal('retreat');setSt(s,'premolt','Sealing the silk retreat before molting');}else setSt(s,'drink','Sipping a water droplet');}if(s.state==='toRetreat'&&!night)setSt(s,'wander','Good morning!');break;}
  case 'premolt':{s.retreat.silk=Math.min(1,s.retreat.silk+dt*.08);if(s.st>3.2)setSt(s,'molt','Molting... please do not disturb');break;}
  case 'sleep':s.retreat.silk=Math.min(1,s.retreat.silk+dt*.02);if(!night&&s.st>(s.wakeD||(s.wakeD=rr(2,25)))){s.wakeD=0;setSt(s,'wander','Woke up - good morning!');}break;
  case 'molt':s.retreat.silk=Math.min(1,s.retreat.silk+dt*.05);if(s.st>14){t.husks.push({type:'exuvia',sp:s.sp,pos:vc(s.pos),size:spSize(s),surf:s.surf,face:vc(s.face),seed:s.seed});s.stage++;s.size=spSize(s);s.meals=0;s.softT=18;toast(`✨ ${s.name} molted! Now stage ${s.stage}/6`);SFX.molt();recordJournal('molt');setSt(s,'rest','Fresh from molting - soft, pale and resting');}break;
  case 'drink':if(s.st>3){s.thirst=0;s.mem.water=memSpot(s);s.obsPts+=.25;if(s.dropT)s.dropT.v-=.6;recordJournal('drink');setSt(s,'look','Refreshed');}break;
  default:setSt(s,'wander');
 }
 holdPrey(s);s.spd=vdist(prev,s.pos)/Math.max(dt,1e-3);if(s.spd>3&&SFX.rustle&&rand()<dt*.12){for(const d of t.decor){if((d.type==='litter'||d.type==='moss')&&Math.abs(s.pos.x-d.x)<d.w*.55&&Math.abs(s.pos.z-d.z)<d.d*.55){SFX.rustle();break;}}}if(s.spd>1&&!s.jump&&['floor','plat','wall','climb'].includes(s.surf.t)){s._silkDist=(s._silkDist||0)+vdist(prev,s.pos);if(s._silkDist>18){addSilk(t,s._silkAnchor||prev,s.pos,'drag',.18);s._silkAnchor=vc(s.pos);s._silkDist=0;}}else if(!s._silkAnchor)s._silkAnchor=vc(s.pos);};

const _v5UpdPrey=updPrey;
updPrey=function(t,p,dt){const oldState=p.state;_v5UpdPrey(t,p,dt);if(p.owner)return;const P_=PREY[p.type];p.scanClock=(p.scanClock||0)-dt;if(p.scanClock<=0){p.scanClock=rr(.8,2.2);
 if(p.type==='cricket'&&['idle','walk'].includes(p.state)&&rand()<.45){p.pauseT=Math.max(p.pauseT||0,rr(.25,.75));}
 if(p.type==='mealworm'&&p.state==='idle'&&!p.buried&&rand()<.45){const edge=pick([v3(3,0,rr(3,TD-3)),v3(TW-3,0,rr(3,TD-3)),v3(rr(3,TW-3),0,3),v3(rr(3,TW-3),0,TD-3)]);p.route=route(t,p,S_FLOOR,edge);setSt(p,'walk');}
 if(p.type==='roach'&&p.state==='idle'&&rand()<.5){const cov=t.decor.filter(d=>DECOR[d.type].cover&&DECOR[d.type].kind!=='plant');if(cov.length){const d=pick(cov),q=v3(clamp(d.x+rr(-4,4),2,TW-2),0,clamp(d.z+rr(-3,3),2,TD-2));if(!groundAt(t,q.x,q.z).p){p.route=route(t,p,S_FLOOR,q);setSt(p,'walk');}}}
 if(p.type==='moth'&&isNight()&&p.state==='idle'&&p.surf.t!=='air'&&rand()<.5)takeOff(t,p,null);
 }
 if(oldState!==p.state&&p.state==='flee')p.alert=1;};

const _v5UpdTank=updTank;
updTank=function(t,dt){t.age=(t.age||0)+dt;t.humidity=lerp(t.humidity??.38,.34,dt/260);_v5UpdTank(t,dt);if(t._removeSpiders&&t._removeSpiders.length){const dead=new Set(t._removeSpiders);t._removeSpiders.length=0;for(let i=t.spiders.length-1;i>=0;i--)if(dead.has(t.spiders[i]))t.spiders.splice(i,1);for(const sp of t.spiders){if(sp.hunt&&dead.has(sp.hunt.prey)){sp.hunt=null;sp.route=null;if(!sp.owner)setSt(sp,'wander','Reassessing the terrarium');}if(sp._huntedBy&&dead.has(sp._huntedBy))sp._huntedBy=null;}if(G.sel&&dead.has(G.sel))G.sel=null;}if(t.silk){for(const l of t.silk){l.age=(l.age||0)+dt;l.alpha=Math.max(.045,l.alpha-dt/1800);}if(t.silk.length>140)t.silk.splice(0,t.silk.length-140);}};

// Independent eye attention: eye highlights drift before the whole body commits to turning.
let EYELOOK=0;
const _v5DrawEye=drawEye;
drawEye=function(cx,cy,r,eyeC){_v5DrawEye(cx,cy,r,eyeC);if(Math.abs(EYELOOK)>.02&&r>.9)pblend(cx+EYELOOK*r*.42,cy-r*.28,0xffffffff,.38);};
const _v5DrawSpiderEnt=drawSpiderEnt;
drawSpiderEnt=function(t,s,c){if(s.owner)return;const sz=spSize(s),S=SPEC[s.sp],v=viewFor(s,c),CS=CSf(c),dp=dispPos(s,sz*.65*CS,c);if(s.surf.t==='plat'){const d=platById(t,s.surf.id);if(d)dp.y=platTopY(d,dp.x,dp.z);}s._dp=dp;const p=Pv(dp,c);if(s.surf.t!=='wall')drawShadow(t,s,sz*.45*CS,c,dp);const a=s.attn&&s.attn.pos?Math.atan2(s.attn.pos.z-s.pos.z,s.attn.pos.x-s.pos.x)-Math.atan2(s.face.z,s.face.x):0;EYELOOK=clamp(Math.sin(a),-1,1);const moving=s.spd>2,frz=!!s._stalkFrozen,twitch=frz&&(s.persona?.twitch??(1-s.tr.patience))>.55,st=s.state,soft=clamp((s.softT||0)/18,0,1);let pal=S.pal;if(soft>0)pal=mixPalT(S.pal,1-soft);if(st==='molt'||st==='premolt')pal=mixPalT(S.pal,.12);const breath=['rest','bask','sleep','premolt'].includes(st)?Math.sin(s.anim*2.2)*.014:0,o={x:p[0],y:p[1],u:c.k*sz/9.5*CS,view:v.view,flip:v.flip,ang:v.ang,pal,pat:S.pat,seed:s.seed,phase:frz?0:(moving?s.anim*16:0),crouch:st==='crouch'?1:(st==='stalk'?.5:0),wig:frz?0:(st==='crouch'?Math.sin(s.anim*30):0),jump:!!(s.jump&&st==='pounce')||st==='fall',groom:frz?(twitch?s.anim:0):(st==='groom'||st==='mistReact'?s.anim:0),raise:['stalk','crouch','watch','notice','inspect','display','threat'].includes(st)?1:0,as:.82+s.sat*.0035+breath,fan:S.pat==='peacock'&&(st==='look'&&Math.sin(s.st*2)>.3)};if(v.view==='top')o.y=p[1];if(st==='sleep'||st==='molt'||st==='premolt'){o.phase=0;o.raise=0;}const hp=s.hunt&&s.hunt.prey;if(hp&&hp.owner===s)o.held=(x,y,view,dir,ang,gy)=>drawHeldPrey(t,hp,c,x,y,view,dir,ang,gy);drawJumper(o);EYELOOK=0;};
const HELD_GRIP={fruitfly:{side:.34,down:.32,top:.42},housefly:{side:.34,down:.32,top:.42},bluebottle:{side:.34,down:.32,top:.42},moth:{side:.48,down:.25,top:.55},cricket:{side:.43,down:.24,top:.43},mealworm:{side:.48,down:.08,top:.48},roach:{side:.40,down:.15,top:.42}};
function heldPal(pal,fade){if(fade<=0)return pal;const o={};for(const k in pal){const a=col(pal[k]),m=mixc(a,0xff8f806f,fade);o[k]='#'+[cr(m),cg(m),cb(m)].map(v=>v.toString(16).padStart(2,'0')).join('');}return o;}
drawHeldPrey=function(t,p,c,x,y,view,dir,ang,gy){const s=p.owner;if(!s)return;const P_=targetProfile(p),struggle=s.hunt&&s.state==='subdue'?clamp(s.hunt.subT/Math.max(.01,P_.struggle||1),0,1):0,carrierU=c.k*spSize(s)/9.5*CSf(c),shake=struggle>0?Math.sin(s.anim*45)*struggle*Math.min(1.2,carrierU*.16):0,top=view==='top'||view==='belly',a=Number.isFinite(ang)?ang:0;
 const spiderLike=p.kind==='spider'||p.type==='sjumper';
 if(spiderLike){const actual=p.kind==='spider',V=actual?SPEC[p.sp]:null,basePal=actual?V.pal:SJPAL,fade=clamp((p.feed||0)*(actual?.55:.42),0,actual?.55:.42),pal=heldPal(basePal,fade),shrink=1-clamp(p.feed||0,0,1)*.22,size=actual?spSize(p):p.size,u=(actual?c.k*size/9.5*CSf(c)*.72:c.k*PSf(c)*size/12)*shrink,pat=actual?V.pat:'stripes';
  if(top){const bite=3.72*u,cx=x+Math.cos(a)*bite-Math.sin(a)*shake,cy=y+Math.sin(a)*bite+Math.cos(a)*shake;drawJumper({x:cx,y:cy,u,view:'top',flip:false,ang:a+Math.PI,pal,pat,seed:p.seed,phase:0,as:.85});}
  else{const sd=dir||((p.seed&1)?1:-1),cx=x+sd*3.18*u,cy=y+3.02*u+shake;drawJumper({x:cx,y:cy,u,view:'side',flip:sd>0,ang:0,pal,pat,seed:p.seed,phase:0,as:.85});}
  return;}
 const grip=HELD_GRIP[p.type]||{side:.36,down:.2,top:.4},o={tw:struggle>0?s.anim*(.5+struggle):0,dark:s.state==='subdue'?(1-struggle)*.5:.5+(p.feed||0)*.4,shrink:1-(p.feed||0)*.3},u=c.k*PSf(c),sz=p.size*u*o.shrink;
 if(top){const bite=grip.top*sz,cx=x+Math.cos(a)*bite-Math.sin(a)*shake,cy=y+Math.sin(a)*bite+Math.cos(a)*shake;drawPrey(p,cx,cy,u,'top',false,a+Math.PI,o);return;}
 const sd=dir||((p.seed&1)?1:-1),cx=x+sd*grip.side*sz,cy=y+grip.down*sz+shake;drawPrey(p,cx,cy,u,'side',sd>0,0,o);};
const _v5DrawHusk=drawHusk;
drawHusk=function(t,h,c){if(h.type==='spiderMeal'){const q=Pv(dispPos({pos:h.pos,surf:h.surf||S_FLOOR},h.size*.6,c),c),S=SPEC[h.sp],v=viewFor({surf:h.surf||S_FLOOR,pos:h.pos,face:h.face||v3(1,0,0)},c);drawJumper({x:q[0],y:q[1],u:c.k*h.size/9.5*CSf(c)*.72,view:v.view,flip:v.flip,ang:v.ang,pal:paleOf(S.pal),pat:S.pat,seed:h.seed,as:.62});return;}_v5DrawHusk(t,h,c);};

function drawPersistentSilk(g,t,c){if(!t.silk||!t.silk.length)return;g.save();g.lineWidth=Math.max(.45,.42*RS);for(const l of t.silk){const a=Pv(l.a,c),b=Pv(l.b,c),al=clamp(l.alpha||.12,.035,.45);g.strokeStyle=`rgba(245,248,250,${al})`;g.beginPath();g.moveTo(a[0],a[1]);const mx=(a[0]+b[0])*.5,my=(a[1]+b[1])*.5+Math.min(2.5,Math.hypot(b[0]-a[0],b[1]-a[1])*.025);g.quadraticCurveTo(mx,my,b[0],b[1]);g.stroke();}g.restore();}
const _v5DrawScene=drawScene;
drawScene=function(t,c){_v5DrawScene(t,c);const base=DLX;DLX=g=>{if(base)base(g);drawPersistentSilk(g,t,c);};};

const _v5SetupCam=setupCam;
// v10: keep Camera 3 geometry scale fixed. The old dramatic zoom changed c.k while
// close-up terrain/decor caches were still reused, which could visually detach the
// substrate and objects from the glass. Cinematic emphasis remains in post FX; the
// physical terrarium projection itself stays stable.
setupCam=function(c,mode){if(mode!==3)return _v5SetupCam(c,mode);c.mode=3;c._wildZoom=1;c.k=5.5*RS;c.ox=W/2-c.fx*c.k;c.oy=H/2+30*RS-(c.fz*.35*c.k-c.fy*c.k);};

const _v5RenderInfo=renderInfo;
renderInfo=function(){_v5RenderInfo();const s=G.sel;if(!s||s.owner)return;const el=$('info');if(!el)return;let row=$('iPersona');if(!row){row=document.createElement('div');row.id='iPersona';row.className='row';row.style.marginTop='4px';const state=$('state');if(state&&state.parentNode)state.parentNode.insertBefore(row,state.nextSibling);}row.innerHTML=`<span>Observed traits: ${personalityLabel(s)}</span>`;};

// Misting changes the microclimate and provokes small natural reactions.
$('mistBtn').onclick=()=>{const t=cur();SFX.mist();t.humidity=Math.min(1,(t.humidity??.38)+.42);for(let i=0;i<16;i++){const w=pick(['z0','x0','xW','zD']),p=wallClamp(w,v3(rr(5,TW-5),rr(8,TH-10),rr(5,TD-5)));t.drops.push({pos:p,surf:{t:'wall',w},v:rr(.7,1)});}for(const d of t.decor)for(const pp of d.perches)if(rand()<.4)t.drops.push({pos:vc(pp),surf:{t:'perch'},v:rr(.5,.9)});for(const p of t.prey){p.alert=clamp((p.alert||0)+.18,0,1);if((p.type==='cricket'||p.type==='roach')&&rand()<.35)preyFlee(t,p,null,false);}for(const sp of t.spiders)if(!sp.owner&&['wander','look','rest','watch','bask'].includes(sp.state)&&rand()<.45){sp.route=null;setSt(sp,'mistReact','A droplet landed nearby');}toast('💧 Misted the tank • humidity rising');};

if(typeof SFX==='object')SFX.rustle=()=>{try{if(SND.ctx)nz(.035,'bandpass',1500,.03);}catch(e){}};

// Save/load v6 fields while remaining compatible with older v5 saves.
save=function(){try{const data={v:13,coins:G.coins,clock:G.clock,catches:G.catches,unlocked:G.unlocked,cur:G.cur,journal:G.journal||{},tanks:G.tanks.map(t=>({sub:t.sub,humidity:t.humidity,age:t.age,decor:t.decor.map(d=>[d.type,d.x,d.z,d.rot,d.seed]),silk:(t.silk||[]).slice(-80).map(l=>({a:l.a,b:l.b,kind:l.kind,alpha:l.alpha,age:l.age})),spiders:t.spiders.filter(s=>!s.owner).map(s=>({sp:s.sp,name:s.name,stage:s.stage,meals:s.meals,sat:s.sat,thirst:s.thirst,tr:s.tr,persona:s.persona,mem:s.mem,catches:s.catches,seed:s.seed,obsPts:s.obsPts,softT:s.softT})),prey:t.prey.filter(p=>!p.owner).map(p=>p.type),husks:t.husks.slice(-40)}))};localStorage.setItem('jumperTerrarium1',JSON.stringify(data));}catch(e){console.warn('save',e);}};
load=function(){try{const d=JSON.parse(localStorage.getItem('jumperTerrarium1')||'null');if(!d)return false;G.coins=d.coins;G.clock=d.clock;G.catches=d.catches||0;G.unlocked=d.unlocked||G.unlocked;G.cur=d.cur||0;G.journal=d.journal||{};JT6.loading=true;G.tanks=d.tanks.map((td,i)=>{const t=makeTank(i);t.sub=td.sub;t.humidity=td.humidity??.38;t.age=td.age||0;for(const [ty,x,z,rot,seed] of td.decor||[])if(DECOR[ty])_v5AddDecor(t,ty,x,z,rot,seed);t.silk=(td.silk||[]).map(l=>({a:v3(l.a.x,l.a.y,l.a.z),b:v3(l.b.x,l.b.y,l.b.z),kind:l.kind,alpha:l.alpha,age:l.age||0}));for(const sd of td.spiders||[]){const sp=newSpider(sd.sp,t);Object.assign(sp,{name:sd.name,stage:sd.stage,meals:sd.meals,sat:sd.sat,thirst:sd.thirst??.2,tr:sd.tr||sp.tr,persona:sd.persona||sp.persona,mem:sd.mem||sp.mem,catches:sd.catches||0,seed:sd.seed,obsPts:sd.obsPts||0,softT:sd.softT||0});sp.size=spSize(sp);const g=groundAt(t,sp.pos.x,sp.pos.z);if(g.p){sp.surf={t:'plat',id:g.p.id};sp.pos.y=g.h;}t.spiders.push(sp);}for(const ty of td.prey||[])if(PREY[ty]){const p=newPrey(ty,t),g=groundAt(t,p.pos.x,p.pos.z);if(g.p){p.surf={t:'plat',id:g.p.id};p.pos.y=g.h;}t.prey.push(p);}if(Array.isArray(td.husks)&&td.husks.length&&typeof td.husks[0]==='object')t.husks=td.husks;return t;});JT6.loading=false;return true;}catch(e){JT6.loading=false;console.warn(e);return false;}};

// Escape closes the journal too.
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal('journalModal');});
// ================= v7 awareness + continuous-facing patch =================
const JT7={ver:7};
const JT8={ver:8,stability:true};
function flatDir(e){const f=v3(e.face?.x||1,0,e.face?.z||0);return vlen(f)>.001?vnorm(f):v3(1,0,0);}
function faceError(e,d){const f=flatDir(e),q=vnorm(v3(d.x,0,d.z));return Math.acos(clamp(vdot(f,q),-1,1));}
function clearHuntLinkV7(s){if(s.hunt&&s.hunt.prey&&s.hunt.prey.kind==='spider'&&s.hunt.prey._huntedBy===s)s.hunt.prey._huntedBy=null;}
function escapeFromV7(t,s,thr){if(!thr)return;const away=vnorm(v3(s.pos.x-thr.pos.x,0,s.pos.z-thr.pos.z)),nm=targetName(thr);if((s.surf.t==='floor'||s.surf.t==='plat')&&jumpRange(s)>18){const q=v3(clamp(s.pos.x+away.x*rr(20,34),3,TW-3),0,clamp(s.pos.z+away.z*rr(20,34),3,TD-3)),g=groundAt(t,q.x,q.z);q.y=g.h;startJump(s,q,g.p?{t:'plat',id:g.p.id}:S_FLOOR,5+spSize(s)*.24,78+s.tr.jump*58);setSt(s,'escape',`Jumping away from ${nm}`);}else{s.route=route(t,s,S_FLOOR,v3(clamp(s.pos.x+away.x*32,3,TW-3),0,clamp(s.pos.z+away.z*32,3,TD-3)));setSt(s,'escape',`Backing away from ${nm}`);}}
function currentTargetScoreV7(s,p){if(!p)return-1e9;const d=vdist(s.pos,p.pos),P_=targetProfile(p),R=jumpRange(s),motion=clamp((p.spd||0)/(P_.walk||10),0,2);let sc=2.2-d/55+motion*.22+(P_.food||8)/80;if(d<R*1.1)sc+=1.2;if(p.kind==='spider'){const adv=spiderPower(s)-spiderPower(p);sc+=clamp(adv/150,-1.5,1.2);if(p.softT>0)sc+=.8;}return sc;}
function awarenessV7(t,s,dt,walk){if(s.owner||s.jump||['pounce','subdue','carry','feed','fall','dangle','molt','premolt','sleep','toMolt'].includes(s.state))return;s._awareT=(s._awareT||0)-dt;if(s._awareT>0)return;s._awareT=.12+(.16*(s.tr.patience||.5));const cur=s.hunt&&targetValid(t,s,s.hunt.prey)?s.hunt.prey:null,curScore=currentTargetScoreV7(s,cur),commit=s.state==='crouch'?1:s.state==='stalk'?clamp(1-vdist(s.pos,cur?.pos||s.pos)/Math.max(1,jumpRange(s)*3),0,.72):0;let danger=null,dd=1e9,best=null,bs=-1e9;
 for(const o of t.spiders){if(o===s||o.owner||o._gone)continue;const d=vdist(s.pos,o.pos);if(d>85||!LOS(t,eyePos(s),o.pos))continue;if(stronger(o,s)&&d<dd){danger=o;dd=d;}if((s.ignore[o.id]||0)>G.clock||!stronger(s,o)&&!o.softT)continue;const sc=currentTargetScoreV7(s,o)+(o.softT>0?.65:0);if(sc>bs){bs=sc;best=o;}}
 if(danger&&dd<Math.max(28,spSize(danger)*2.2)){clearHuntLinkV7(s);s.hunt=null;s.route=null;s.attn={kind:'spider',id:danger.id,pos:vc(danger.pos)};s._resumeTarget=null;recordJournal('threat');escapeFromV7(t,s,danger);return;}
 for(const p of t.prey){if(!targetValid(t,s,p)||(s.ignore[p.id]||0)>G.clock)continue;const d=vdist(s.pos,p.pos);if(d>78||!LOS(t,eyePos(s),p.pos))continue;const P_=targetProfile(p);const looming=(P_.danger&&p.size>spSize(s)*.72)||(p.size>spSize(s)*1.45);if(p!==cur&&looming&&d<Math.max(15,p.size*1.7)&&rand()<.42+(1-s.tr.bold)*.42){clearHuntLinkV7(s);s.hunt=null;s.route=null;s.attn={kind:p.kind,id:p.id,pos:vc(p.pos)};escapeFromV7(t,s,p);return;}if(p.size>spSize(s)*(1.3+s.tr.bold*.8)||(P_.danger&&s.tr.bold<.35))continue;let sc=currentTargetScoreV7(s,p);if(p!==cur&&d<jumpRange(s)*.72&&!preyWatching(p,s))sc+=1.05;if(sc>bs){bs=sc;best=p;}}
 if(!best||best===cur)return;const margin=.42+s.tr.patience*.6+commit*1.2;if(bs>curScore+margin){clearHuntLinkV7(s);s.hunt={prey:best};s.route=null;s.attn={kind:best.kind,id:best.id,pos:vc(best.pos)};if(best.kind==='spider')best._huntedBy=s;const d=vdist(s.pos,best.pos);if(d<jumpRange(s)*.72&&!preyWatching(best,s)&&s.state==='stalk'){s.hunt={prey:best,t0:G.clock,replans:0,plan:vc(best.pos),lost:0,burst:0,creep:true,cool:1};setSt(s,'crouch',`Opportunistic angle on ${targetName(best)}`);}else setSt(s,'notice',`Attention switched to ${targetName(best)}`);return;}
 const distractChance=(s.persona?.twitch||.3)*.45+(s.persona?.curiosity||.5)*.24;if(cur&&s.state==='stalk'&&commit<.55&&rand()<distractChance){s._resumeTarget=cur;s._distractObj=best;s._distractDur=rr(.35,1.05)*(1.2-s.tr.patience*.35);s.route=null;s.attn={kind:best.kind,id:best.id,pos:vc(best.pos)};setSt(s,'distract',`Distracted by ${targetName(best)}`);}}

// While stalking from glass, keep the exit point laterally aligned with the live prey bearing.
// The vertical goal (usually the bottom edge) stays intact, but the path bends smoothly as prey moves.
function liveWallTrackV19(s,p){if(!s||!p||!s.route||!s.route.length||s.surf.t!=='wall')return;const seg=s.route[0];if(!seg.surf||seg.surf.t!=='wall'||seg.surf.w!==s.surf.w)return;const q=wallClamp(s.surf.w,p.pos);if(s.surf.w==='z0'||s.surf.w==='zD')seg.pt.x=q.x;else seg.pt.z=q.z;if(p.surf&&p.surf.t==='wall'&&p.surf.w===s.surf.w)seg.pt.y=q.y;}

// Walkers rotate toward their actual travel vector before advancing. This removes accidental crab-walking
// while preserving explicit stationary tracking and wall/climb motion.
const _v6FollowRouteV7=followRoute;
followRoute=function(t,e,spd,dt,lockFace){if(!e.route||!e.route.length)return true;const seg=e.route[0];if(seg.hop){if(!e.jump)startJump(e,seg.pt,seg.surf,Math.max(5,vdist(e.pos,seg.pt)*.25),spd*4.5);return false;}
 if(e.kind==='spider'&&seg.climb&&!sameSurf(e.surf,seg.surf)){const key=(seg.surf.id||'')+':'+Math.round(seg.pt.x)+':'+Math.round(seg.pt.z);if(e._probeKey!==key){e._probeKey=key;e._probeT=.18+.12*(e.persona?1-e.persona.activity:.5);}if(e._probeT>0){e._probeT-=dt;faceToward(e,seg.pt,7,dt);e.spd=0;return false;}e._probeKey='';recordJournal('silk');}
 if(!sameSurf(e.surf,seg.surf))e.surf=seg.surf;const d=vsub(seg.pt,e.pos),L=vlen(d);if(L<.001){e.route.shift();return !e.route.length;}const nd=vmul(d,1/L),flat=e.kind==='spider'&&!seg.climb&&(e.surf.t==='floor'||e.surf.t==='plat'||e.surf.t==='perch'),wallWalk=e.kind==='spider'&&!seg.climb&&e.surf.t==='wall';let align=1,moveDir=nd;if(flat){const err=faceError(e,nd);turnFaceFlat(e,nd,9+(e.persona?.activity||.5)*2.5,dt);align=err>.52?0:err>.30?.35:err>.16?.72:1;}else if(wallWalk){const before=wallPlaneDir(e.surf.w,e.face)||nd;const want=wallPlaneDir(e.surf.w,nd)||nd;const err=Math.acos(clamp(vdot(before,want),-1,1));turnFaceWall(e,want,7.5+(e.persona?.activity||.5)*2.2,dt,.025);align=err>1.05?.18:err>.62?.48:err>.30?.78:1;moveDir=wallPlaneDir(e.surf.w,e.face)||want;}const step=spd*dt*(seg.climb?.64:1)*align;
 if(L<=Math.max(step,.01)+.01){if(step<=.001)return false;e.pos=vc(seg.pt);if(e.surf.t==='plat'){const pd=platById(t,e.surf.id);if(pd)e.pos.y=platTopY(pd,e.pos.x,e.pos.z);}e.route.shift();if(!e.route.length){if(seg.surf.t!=='climb')clampSurf(t,e);return true;}return false;}
 if(step<=.001)return false;e.pos=vadd(e.pos,vmul(moveDir,step));if(e.surf.t==='plat'){const pd=platById(t,e.surf.id);if(pd)e.pos.y=platTopY(pd,e.pos.x,e.pos.z);}if(wallWalk)clampSurf(t,e);e.moved+=step;if(!flat&&!wallWalk&&(!lockFace||seg.climb||e.surf.t==='wall'))e.face=vnorm(d);return false;};

// Flat-surface spiders now use the exact projected heading instead of snapping to one of eight sectors.
const _v6ViewForV7=viewFor;
viewFor=function(e,c){const s=e.surf;if(s&&(s.t==='wall'||s.t==='climb'||s.t==='silk'))return _v6ViewForV7(e,c);const f=flatDir(e),a=Pv(e.pos,c),b=Pv(vadd(e.pos,vmul(f,5)),c),ang=Math.atan2(b[1]-a[1],b[0]-a[0]),front=clamp(vdot(f,viewDir(c)),-1,1);return {view:'free',ang,front,flip:Math.cos(ang)<0};};
function drawJumperFree(o){const pal=o.pal,u=o.u,X=o.x,Y=o.y,L=col(pal.leg),LB=col(pal.band),LT=shd(L,.6),F=col(pal.fuzz),eyeC=pal.eye?col(pal.eye):0,ph=o.phase||0,cr=o.crouch||0,fr=clamp(o.front??0,-1,1),af=Math.abs(fr),axis=.98-af*.34,side=.96+af*.08,a=o.ang||0,ca=Math.cos(a),sa=Math.sin(a),la=-sa,lb=ca,as=o.as||1,ant=o.pat==='ant'?.65:1,abd=abdShader(pal,o.pat,o.seed,o.fan),car=carShader(pal,o.pat,o.seed),lt=Math.max(1,u*.8),gaze=clamp(o.gaze||0,-1,1);
 const T=(f,l)=>[X+(ca*f*axis+la*l*side)*u,Y+(sa*f*axis+lb*l*side)*u];const bodyAng=Math.atan2(sa*axis,ca*axis),by=-cr*.35-(o.jump?.35:0);const leg=(i,sd)=>{const w=Math.sin(ph+i*1.57+(sd>0?Math.PI:0)),lift=Math.max(0,w)*(.45+.35*(1-af)),hip=T(1.1-i*.68,sd*(1.25+i*.08)),knee=T(2.35-i*1.48,sd*(2.65+i*.46)),foot=T(3.5-i*2.35+Math.cos(ph+i*1.57)*.28,sd*(3.5+i*.6));if(o.jump){foot[0]+=ca*(i<2?1.4:-1.4)*u;foot[1]+=sa*(i<2?1.4:-1.4)*u;}else{foot[0]-=la*lift*u*.18;foot[1]-=lb*lift*u*.18;}if(i===0&&o.raise){knee[0]+=ca*.4*u;knee[1]+=sa*.4*u;foot[0]+=ca*.8*u;foot[1]+=sa*.8*u;}return[hip,knee,foot];};
 const farSide=fr>=0?-1:1;for(let i=3;i>=0;i--)drawLeg(leg(i,farSide),lt*.88,shd(L,.66),shd(LB,.72),LT);const ap=T(-3.0-(o.wig||0)*.3,0),cp=T(1.05,0);
 if(fr<0){pshade(cp[0],cp[1],2.6*u,2.0*u,bodyAng,car);pshade(ap[0],ap[1],3.0*as*u*ant,2.35*as*u*(o.fan?1.22:1),bodyAng,abd);}else{pshade(ap[0],ap[1],2.95*as*u*ant,2.3*as*u*(o.fan?1.22:1),bodyAng,abd);pshade(cp[0],cp[1],2.65*u,2.05*u,bodyAng,car);}const fuzzN=u>2?8:3;for(let i=0;i<fuzzN;i++){const aa=hash3(i,31,o.seed)*6.283,q=T(-3+Math.cos(aa)*2.6,Math.sin(aa)*2.0);pblend(q[0],q[1],F,.42);}
 if(fr>-.35){const face=T(2.45,.2*gaze),fc=col(pal.face);GLOSS=.08;pshade(face[0],face[1],(1.35+.6*fr)*u,(1.0+.25*fr)*u,bodyAng,()=>fc);GLOSS=.18;const spread=.68+.38*(1-fr),forward=2.85+.18*fr;for(const sd of [-1,1]){const e=T(forward,sd*spread+.16*gaze);drawEye(e[0],e[1],Math.max(.55,(.78+.24*fr)*u),eyeC);const es=T(2.35,sd*(1.55+.2*(1-fr)));drawEye(es[0],es[1],Math.max(.4,.4*u),eyeC);}const ch=col(pal.chel),chh=col(pal.chelHi);for(const sd of [-1,1]){const q=T(3.55,sd*.48+.12*gaze);GLOSS=1;pshade(q[0],q[1],.5*u,.78*u,bodyAng,(uu,vv,r2,rim)=>rim?shd(ch,.6):(vv<-.15?chh:ch));GLOSS=.18;}const gp=o.groom?Math.sin(o.groom*14)*.5:0;for(const sd of [-1,1]){const q=T(3.95,sd*.78+.18*gaze);pell(q[0],q[1]-gp*sd*u*.35,.5*u,.55*u,F);}}else{for(const sd of [-1,1]){const e=T(2.45,sd*1.2);drawEye(e[0],e[1],Math.max(.4,.34*u),eyeC);}}
 if(o.held){const h=T(4.2,.18*gaze);o.held(h[0],h[1],'top',0,a,Y);}for(let i=0;i<4;i++)drawLeg(leg(i,-farSide),i===0?lt*1.2:lt,L,LB,LT);}
const _v6DrawJumperV7=drawJumper;
drawJumper=function(o){if(o.view==='free')return drawJumperFree(o);return _v6DrawJumperV7(o);};

// Pass exact attention offset into the continuous pose so the face/eyes visibly lead body turns.
const _v6DrawSpiderEntV7=drawSpiderEnt;
drawSpiderEnt=function(t,s,c){if(s.owner)return;const sz=spSize(s),S=SPEC[s.sp],v=viewFor(s,c),CS=CSf(c),dp=dispPos(s,sz*.65*CS,c);if(s.surf.t==='plat'){const d=platById(t,s.surf.id);if(d)dp.y=platTopY(d,dp.x,dp.z);}s._dp=dp;const p=Pv(dp,c);if(s.surf.t!=='wall')drawShadow(t,s,sz*.45*CS,c,dp);const rel=s.attn&&s.attn.pos?Math.atan2(s.attn.pos.z-s.pos.z,s.attn.pos.x-s.pos.x)-Math.atan2(s.face.z,s.face.x):0;EYELOOK=clamp(Math.sin(rel),-1,1);const moving=s.spd>2,frz=!!s._stalkFrozen,twitch=frz&&(s.persona?.twitch??(1-s.tr.patience))>.55,st=s.state,soft=clamp((s.softT||0)/18,0,1);let pal=S.pal;if(soft>0)pal=mixPalT(S.pal,1-soft);if(st==='molt'||st==='premolt')pal=mixPalT(S.pal,.12);const breath=['rest','bask','sleep','premolt'].includes(st)?Math.sin(s.anim*2.2)*.014:0,o={x:p[0],y:p[1],u:c.k*sz/9.5*CS,view:v.view,flip:v.flip,ang:v.ang,front:v.front,gaze:EYELOOK,pal,pat:S.pat,seed:s.seed,phase:frz?0:(moving?s.anim*16:0),crouch:st==='crouch'?1:(st==='stalk'?.5:0),wig:frz?0:(st==='crouch'?Math.sin(s.anim*30):0),jump:!!(s.jump&&st==='pounce')||st==='fall',groom:frz?(twitch?s.anim:0):(st==='groom'||st==='mistReact'?s.anim:0),raise:['stalk','crouch','watch','notice','inspect','display','threat','distract'].includes(st)?1:0,as:.82+s.sat*.0035+breath,fan:S.pat==='peacock'&&(st==='look'&&Math.sin(s.st*2)>.3)};if(st==='sleep'||st==='molt'||st==='premolt'){o.phase=0;o.raise=0;}const hp=s.hunt&&s.hunt.prey;if(hp&&hp.owner===s)o.held=(x,y,view,dir,ang,gy)=>drawHeldPrey(t,hp,c,x,y,view,dir,ang,gy);drawJumper(o);EYELOOK=0;};

// Tiny-jumper live food uses the same continuous flat pose instead of falling back to a side sprite.
const _v6DrawPreyEntV7=drawPreyEnt;
drawPreyEnt=function(t,p,c){if(p.type!=='sjumper')return _v6DrawPreyEntV7(t,p,c);if(p.buried)return;const v=viewFor(p,c),PS=PSf(c);let dp=dispPos(p,p.size*.55*PS,c);if(p.surf&&p.surf.t==='plat'&&!p.owner){const d=platById(t,p.surf.id);if(d)dp.y=platTopY(d,dp.x,dp.z);}if(p.owner&&p.owner._dp)dp=vadd(dp,vsub(p.owner._dp,p.owner.pos));const q=Pv(dp,c);if(!p.owner&&p.surf.t!=='wall')drawShadow(t,p,p.size*.35*PS,c,dp);drawJumper({x:q[0],y:q[1],u:c.k*PS*p.size/12,view:v.view,flip:v.flip,ang:v.ang,front:v.front,pal:SJPAL,pat:'stripes',seed:p.seed,phase:p.anim*12*(p.spd>1?1:0),as:1});};
// Exuviae and spider remains preserve the exact continuous facing at the moment they were left behind.
const _v6DrawHuskV7=drawHusk;
drawHusk=function(t,h,c){if(h.type==='exuvia'||h.type==='spiderMeal'){const ent={surf:h.surf||S_FLOOR,pos:h.pos,face:h.face||v3(1,0,0)},q=Pv(dispPos(ent,h.size*.6,c),c),S=SPEC[h.sp],v=viewFor(ent,c),pal=h.type==='spiderMeal'?paleOf(S.pal):paleOf(S.pal);drawJumper({x:q[0],y:q[1],u:c.k*h.size/9.5*CSf(c)*(h.type==='spiderMeal'?.72:1),view:v.view,flip:v.flip,ang:v.ang,front:v.front,pal,pat:S.pat,seed:h.seed,as:h.type==='spiderMeal'?.62:.8});return;}return _v6DrawHuskV7(t,h,c);};
// ================= end v7 patch =================
