// ================= v15 habitat expansion =================
const JT15={ver:15,activeTank:null};
const TANK_TYPES={
 standard:{name:'Standard Terrarium',short:'Standard',w:200,d:90,h:100,shape:'rect',cap:3,price:0,icon:'▭',groups:['wood','rock','ground','flower','foliage','utility','cozy','small','vertical'],presets:['corkForest','flowerGarden','oldForest','spiderParadise','overgrownRuin']},
 arboreal:{name:'Tall Arboreal',short:'Arboreal',w:150,d:78,h:150,shape:'rect',cap:3,price:80,icon:'▯',groups:['wood','ground','flower','foliage','utility','small','vertical'],presets:['canopyTower','verticalHunter','bromeliadWall','vineColumn','rainforest']},
 wide:{name:'Wide Display',short:'Wide',w:270,d:82,h:88,shape:'rect',cap:4,price:105,icon:'▬',groups:['wood','rock','ground','flower','foliage','utility','cozy','small'],presets:['dryWoodland','rockyCanyon','meadowRun','longHunt','flowerVerge']},
 nano:{name:'Nano Cube',short:'Nano',w:118,d:68,h:82,shape:'rect',cap:1,price:35,icon:'▫',groups:['ground','flower','foliage','utility','small','breeder'],presets:['slingNursery','minimalBreeder','mossCup','tinyJungle']},
 cube:{name:'Large Cube',short:'Cube',w:165,d:132,h:145,shape:'rect',cap:4,price:135,icon:'□',groups:['wood','rock','ground','flower','foliage','utility','cozy','small','vertical'],presets:['deepJungle','rootCathedral','layeredRock','mushroomGrove','cubeParadise']},
 acrylic:{name:'Acrylic Breeder',short:'Acrylic',w:135,d:72,h:96,shape:'rect',cap:2,price:55,icon:'▣',groups:['wood','ground','foliage','utility','small','breeder'],presets:['cleanBreeder','corkStrip','feedingLedge','dryMinimal']},
 panoramic:{name:'Panoramic Habitat',short:'Panoramic',w:310,d:98,h:112,shape:'rect',cap:4,price:225,icon:'▰',groups:['wood','rock','ground','flower','foliage','utility','cozy','small','vertical'],presets:['woodlandPanorama','gardenWalk','canyonRun','showcaseJungle','panoramicRuin']},
 jar:{name:'Tall Display Jar',short:'Jar',w:132,d:132,h:155,shape:'round',cap:2,price:165,icon:'◯',groups:['wood','ground','flower','foliage','utility','small','vertical'],presets:['jarJungle','mossLantern','vineSpiral','flowerJar','verticalJar']}
};
const SLOT_PRICE15=[0,0,0,120,180,260,360,480];
function tankType(t){return TANK_TYPES[t?.tankType]||TANK_TYPES.standard;}
function tankCapacity(t){return tankType(t).cap;}
function setTankDims(t){const q=tankType(t);TW=q.w;TD=q.d;TH=q.h;JT15.activeTank=t||null;return q;}
function withTankDims(t,fn){const a=TW,b=TD,c=TH,o=JT15.activeTank;setTankDims(t);try{return fn();}finally{TW=a;TD=b;TH=c;JT15.activeTank=o;}}
function isRoundTank(t=JT15.activeTank){return tankType(t).shape==='round';}
function insideTankXZ(t,x,z,m=0){const T=tankType(t);if(T.shape!=='round')return x>=m&&x<=T.w-m&&z>=m&&z<=T.d-m;const rx=Math.max(1,T.w*.5-m),rz=Math.max(1,T.d*.5-m),dx=(x-T.w*.5)/rx,dz=(z-T.d*.5)/rz;return dx*dx+dz*dz<=1;}
function clampTankXZ(t,p,m=1.5){const T=tankType(t);if(T.shape!=='round'){p.x=clamp(p.x,m,T.w-m);p.z=clamp(p.z,m,T.d-m);return p;}const cx=T.w*.5,cz=T.d*.5,rx=Math.max(2,T.w*.5-m),rz=Math.max(2,T.d*.5-m),dx=(p.x-cx)/rx,dz=(p.z-cz)/rz,l=Math.hypot(dx,dz);if(l>1){p.x=cx+dx/l*rx;p.z=cz+dz/l*rz;}return p;}
function clearTankCaches15(t){t.bgKey='';t.bg=null;t.stat=null;for(const d of t.decor){d.cache=null;d._cache8=null;d._cache8Order=null;}if(typeof FGC==='object')for(const k in FGC)delete FGC[k];}

// Existing decor metadata.
const DGR={
 bark:['wood'],tower:['wood','vertical'],drift:['wood'],stone:['rock','small'],slate:['rock'],bonsai:['foliage','cozy'],moss:['ground','small'],litter:['ground','small'],dish:['utility','small','breeder'],pebbles:['ground','rock','small'],fern:['foliage'],pinkfl:['flower'],daisy:['flower'],lav:['flower','vertical'],grass:['foliage','vertical'],succ:['foliage','small'],shroom:['foliage','cozy','small'],tree:['foliage','vertical']
};
for(const [id,g] of Object.entries(DGR))if(DECOR[id])DECOR[id].groups=g;
function addD(id,o){DECOR[id]=Object.assign({groups:['ground']},o);}
// Wood / climbing / functional structures.
addD('corktube',{name:'Cork Tube',price:28,kind:'plat',w:20,d:18,h:42,tex:'cork',cat:'decor',groups:['wood','vertical']});
addD('corkround',{name:'Cork Round',price:18,kind:'plat',w:28,d:24,h:12,tex:'cork',cat:'decor',groups:['wood','small']});
addD('corkslab',{name:'Cork Slab',price:26,kind:'plat',w:56,d:14,h:20,tex:'cork',cat:'decor',groups:['wood']});
addD('corkledge',{name:'Cork Ledge',price:20,kind:'plat',w:34,d:13,h:10,tex:'cork',cat:'decor',groups:['wood','utility','small']});
addD('branch',{name:'Branch Perch',price:18,kind:'plat',w:54,d:9,h:16,tex:'drift',cat:'decor',groups:['wood','vertical']});
addD('forkbranch',{name:'Forked Branch',price:28,kind:'plat',w:66,d:10,h:27,tex:'drift',cat:'decor',groups:['wood','vertical']});
addD('grapevine',{name:'Grapevine',price:25,kind:'plat',w:48,d:9,h:28,tex:'drift',cat:'decor',groups:['wood','vertical']});
addD('rootarch',{name:'Root Arch',price:30,kind:'plat',w:46,d:18,h:20,tex:'drift',cat:'decor',groups:['wood','cozy']});
addD('hollowlog',{name:'Hollow Log',price:24,kind:'plat',w:42,d:22,h:16,tex:'cork',cat:'decor',groups:['wood','cozy']});
addD('feedingledge',{name:'Feeding Ledge',price:14,kind:'plat',w:24,d:13,h:8,tex:'slate',cat:'decor',groups:['utility','small','breeder']});
addD('maghide',{name:'Magnetic Hide',price:24,kind:'plat',w:26,d:18,h:18,tex:'cork',cat:'decor',groups:['utility','wood','vertical','breeder']});
addD('rockcave',{name:'Rock Cave',price:28,kind:'plat',w:40,d:28,h:18,tex:'stone',cat:'decor',groups:['rock','cozy']});
addD('sandstone',{name:'Sandstone Shelf',price:18,kind:'plat',w:34,d:24,h:12,tex:'stone',cat:'decor',groups:['rock']});
addD('riverstone',{name:'River Stone',price:10,kind:'plat',w:24,d:18,h:8,tex:'stone',cat:'decor',groups:['rock','small']});
addD('slateledge',{name:'Slate Ledge',price:17,kind:'plat',w:44,d:18,h:10,tex:'slate',cat:'decor',groups:['rock','utility']});
addD('ruin',{name:'Mini Ruin',price:34,kind:'plat',w:36,d:26,h:22,tex:'stone',cat:'decor',groups:['rock','cozy']});
addD('bridge',{name:'Tiny Wooden Bridge',price:26,kind:'plat',w:48,d:16,h:12,tex:'drift',cat:'decor',groups:['wood','cozy']});
addD('brokenpot',{name:'Broken Flowerpot',price:14,kind:'plat',w:26,d:22,h:12,tex:'pot',cat:'decor',groups:['cozy','small']});
addD('mosspole',{name:'Moss Pole',price:24,kind:'plat',w:14,d:14,h:60,tex:'cork',cat:'decor',groups:['vertical','wood','foliage']});
addD('woodhide',{name:'Wood Hide',price:19,kind:'plat',w:32,d:26,h:15,tex:'cork',cat:'decor',groups:['wood','cozy','breeder']});
// Plants. renderAs reuses the established procedural plant language with new proportions.
addD('pothos',{name:'Pothos',price:20,kind:'plant',w:26,d:18,h:52,cover:true,perch:true,cat:'plants',renderAs:'fern',groups:['foliage','vertical']});
addD('ivy',{name:'Creeping Ivy',price:16,kind:'plant',w:24,d:16,h:38,cover:true,perch:true,cat:'plants',renderAs:'fern',groups:['foliage']});
addD('bromeliad',{name:'Bromeliad',price:22,kind:'plant',w:24,d:22,h:22,cover:true,cat:'plants',renderAs:'succ',groups:['foliage','small']});
addD('fittonia',{name:'Fittonia',price:16,kind:'plant',w:25,d:18,h:24,cover:true,cat:'plants',renderAs:'fern',groups:['foliage','small']});
addD('airplant',{name:'Air Plant',price:14,kind:'plant',w:18,d:16,h:22,cover:true,perch:true,cat:'plants',renderAs:'grass',groups:['foliage','small','breeder']});
addD('orchid',{name:'Mini Orchid',price:24,kind:'plant',w:20,d:16,h:38,perch:true,attract:true,fc:'#d998e8',fc2:'#fff0ff',cat:'plants',groups:['flower','vertical']});
addD('palm',{name:'Mini Palm',price:28,kind:'plant',w:24,d:20,h:58,cover:true,perch:true,cat:'plants',renderAs:'tree',groups:['foliage','vertical']});
addD('vine',{name:'Climbing Vine',price:18,kind:'plant',w:16,d:14,h:62,cover:true,perch:true,cat:'plants',renderAs:'grass',groups:['foliage','vertical']});
addD('spiderplant',{name:'Spider Plant',price:17,kind:'plant',w:24,d:18,h:32,cover:true,perch:true,cat:'plants',renderAs:'grass',groups:['foliage','small']});
addD('redflower',{name:'Red Wildflowers',price:18,kind:'plant',w:20,d:14,h:30,perch:true,attract:true,fc:'#e75a4d',fc2:'#ffd0b8',cat:'plants',groups:['flower']});
addD('clover',{name:'Clover Patch',price:12,kind:'plant',w:24,d:18,h:16,cover:true,cat:'plants',renderAs:'fern',groups:['foliage','small']});
addD('mossbush',{name:'Moss Rosette',price:13,kind:'plant',w:20,d:18,h:13,cover:true,cat:'plants',renderAs:'succ',groups:['foliage','small']});
// Ground clutter / micro decor.
addD('oakleaf',{name:'Oak Leaf Litter',price:5,kind:'flat',w:36,d:26,cover:true,cat:'decor',renderAs:'litter',groups:['ground','small']});
addD('magnolialeaf',{name:'Magnolia Leaves',price:6,kind:'flat',w:34,d:24,cover:true,cat:'decor',renderAs:'litter',groups:['ground','small']});
addD('seedpods',{name:'Seed Pods',price:5,kind:'flat',w:22,d:16,cat:'decor',renderAs:'pebbles',groups:['ground','small']});
addD('pinecones',{name:'Pinecones',price:6,kind:'flat',w:24,d:18,cover:true,cat:'decor',renderAs:'pebbles',groups:['ground','small']});
addD('barkchips',{name:'Bark Chips',price:5,kind:'flat',w:32,d:24,cover:true,cat:'decor',renderAs:'litter',groups:['ground','small','breeder']});
addD('lichen',{name:'Lichen Patch',price:7,kind:'flat',w:30,d:22,cover:true,cat:'decor',renderAs:'moss',groups:['ground','small']});
addD('twigs',{name:'Twig Scatter',price:5,kind:'flat',w:34,d:20,cover:true,cat:'decor',renderAs:'litter',groups:['ground','small','breeder']});
addD('driedflowers',{name:'Dried Flowers',price:7,kind:'flat',w:28,d:20,cover:true,cat:'decor',renderAs:'litter',groups:['ground','cozy','small']});

function tankAllowsDecor(t,id){const D=DECOR[id],T=tankType(t);if(!D)return false;if(D.types&&!D.types.includes(t.tankType))return false;const gs=D.groups||['ground'];if(!gs.some(g=>T.groups.includes(g)))return false;if(D.w>T.w-8||D.d>T.d-8||(D.h||D.ph||0)>T.h-5)return false;if(t.tankType==='nano'&&Math.max(D.w,D.d,D.h||0)>44&&!gs.includes('small'))return false;if(t.tankType==='acrylic'&&gs.includes('cozy')&&!gs.includes('breeder'))return false;if(t.tankType==='jar'&&D.w>55)return false;return true;}

const _addDecor15=addDecor;
addDecor=function(t,type,x,z,rot=0,seed){const D=DECOR[type];if(!D)return null;const it=_addDecor15(t,type,x,z,rot,seed);if(!it)return it;const a=D.renderAs,R=rng((it.seed^0x15a11)>>>0);if(a==='fern'&&!it.fronds){it.fronds=[];for(let i=0;i<9;i++){const L=D.h*(.58+R()*.45);it.fronds.push({a:(i/8-.5)*2.6+(R()-.5)*.3,L,dz:(R()-.5)*D.d*.6});}for(const f of it.fronds){const q=fernFrond(it,f)[12];it.perches.push(v3(q[0],q[1]+1,q[2]));}}
 if(a==='grass'&&!it.blades){it.blades=[];for(let i=0;i<14;i++){const L=D.h*(.45+R()*.55);it.blades.push({bx:(R()-.5)*D.w*.7,bz:(R()-.5)*D.d*.6,L,bend:(R()-.5)*14});}for(let i=0;i<4;i++){const b=it.blades[i];it.perches.push(v3(x+b.bx+b.bend*.8,b.L*.9,z+b.bz));}}
 if(a==='tree'&&!it.blobs){it.blobs=[];for(let i=0;i<7;i++)it.blobs.push({bx:(R()-.5)*Math.min(30,D.w*1.4),by:D.h*(.74+R()*.24)-5,bz:(R()-.5)*Math.min(12,D.d*.65),r:5+R()*4});for(const b of treeBlobs(it).slice(0,3))it.perches.push(v3(b.x,b.y+b.r*.8,b.z));}
 for(const p of it.perches){clampTankXZ(t,p,1.5);p.y=Math.min(p.y,tankType(t).h-3);}return it;};
const _drawPlant15=drawPlant;
drawPlant=function(cp,d){const D=DECOR[d.type],a=D&&D.renderAs;if(!a)return _drawPlant15(cp,d);withCanvas(x=>{if(a==='fern')paintFern(x,cp,d);else if(a==='grass')paintGrass(x,cp,d);else if(a==='succ')paintSucc(x,cp,d);else if(a==='shroom')paintShroom(x,cp,d);else if(a==='tree')paintTree(x,cp,d,false);else _drawPlant15(cp,d);});};
const _flatColor15=flatColor;
flatColor=function(d,x,z){const D=DECOR[d.type];if(D&&D.renderAs){const q=Object.assign({},d,{type:D.renderAs});return _flatColor15(q,x,z);}return _flatColor15(d,x,z);};
const _plantBox15=plantBox;
plantBox=function(d,D){if(D&&D.renderAs==='tree'){const ex=Math.max(22,D.w*.8),ez=Math.max(16,D.d*.8),y1=Math.min(TH,(D.h||10)+14);return boxPts(d.x-ex,d.z-ez,d.x+ex,d.z+ez,-2,y1);}return _plantBox15(d,D);};

const _makeTank15=makeTank;
makeTank=function(i){const t=_makeTank15(i);t.slot=i;t.tankType=t.tankType||'standard';t.owned=i<3;t.name=t.name||`Tank ${i+1}`;t.presetRoll=0;t.lastPreset=null;t._bgAccum=0;return t;};
const _cur15=cur;
cur=function(){const t=_cur15();if(t)setTankDims(t);return t;};
const _wallClamp15=wallClamp;
wallClamp=function(w,p){const t=JT15.activeTank;if(!t||!isRoundTank(t))return _wallClamp15(w,p);const T=tankType(t),q=vc(p),cx=T.w*.5,cz=T.d*.5,rx=T.w*.5-.45,rz=T.d*.5-.45;q.y=clamp(q.y,0,T.h-4);if(w==='z0'||w==='zD'){q.x=clamp(q.x,cx-rx+.8,cx+rx-.8);const nx=(q.x-cx)/rx,zz=rz*Math.sqrt(Math.max(0,1-nx*nx));q.z=cz+(w==='z0'?-zz:zz);}else{q.z=clamp(q.z,cz-rz+.8,cz+rz-.8);const nz=(q.z-cz)/rz,xx=rx*Math.sqrt(Math.max(0,1-nz*nz));q.x=cx+(w==='x0'?-xx:xx);}return q;};
const _wallBase15=wallBase;
wallBase=function(w,p){const t=JT15.activeTank;if(!t||!isRoundTank(t))return _wallBase15(w,p);const q=wallClamp(w,p),T=tankType(t),cx=T.w*.5,cz=T.d*.5,n=vnorm(v3(cx-q.x,0,cz-q.z));q.y=0;return v3(q.x+n.x*1.8,0,q.z+n.z*1.8);};
const _clampSurf15=clampSurf;
clampSurf=function(t,e){_clampSurf15(t,e);if(!t)return;if(e.surf&&e.surf.t==='floor')clampTankXZ(t,e.pos,1.5);else if(e.surf&&e.surf.t==='air')clampTankXZ(t,e.pos,.8);};
const _randFloor15=randFloorPt;
randFloorPt=function(t){if(!isRoundTank(t))return _randFloor15(t);const T=tankType(t);for(let i=0;i<30;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*.86,p=v3(T.w*.5+Math.cos(a)*T.w*.5*r,0,T.d*.5+Math.sin(a)*T.d*.5*r);if(groundAt(t,p.x,p.z).h===0)return p;}return v3(T.w*.5,0,T.d*.5);};
const _route15=route;
route=function(t,e,toS,toP,hopRange=0){const r=_route15(t,e,toS,toP,hopRange);if(isRoundTank(t))for(const q of r)if(q.pt&&(q.surf?.t==='floor'||q.surf?.t==='air'))clampTankXZ(t,q.pt,1.8);return r;};

function canPlaceDecor15(t,id,x,z,rot=0){const D=DECOR[id];if(!D||!tankAllowsDecor(t,id))return false;let w=D.w,d=D.d;if(rot&&D.kind==='plat')[w,d]=[d,w];const pts=[[x-w/2,z-d/2],[x+w/2,z-d/2],[x+w/2,z+d/2],[x-w/2,z+d/2]];if(!pts.every(q=>insideTankXZ(t,q[0],q[1],1)))return false;if(D.kind==='plat'){for(const o of plats(t))if(x-w/2<o.x1&&x+w/2>o.x0&&z-d/2<o.z1&&z+d/2>o.z0)return false;}return true;}
const _placeOK15=placeOK;
placeOK=function(t,pl,x,z){if(pl.kind==='prey')return insideTankXZ(t,x,z,2);return canPlaceDecor15(t,pl.id,x,z,UI.rot);};
function fitDecorPos15(t,id,x,z,rot=0){const D=DECOR[id];let w=D.w,d=D.d;if(rot&&D.kind==='plat')[w,d]=[d,w];const p=v3(x,0,z);clampTankXZ(t,p,Math.max(w,d)*.55+1);return p;}
function enforceTankBounds15(t){for(const e of [...t.spiders,...t.prey]){if(!e||!e.pos)continue;if(e.surf?.t==='wall'){const q=wallClamp(e.surf.w,e.pos);e.pos.x=q.x;e.pos.z=q.z;e.pos.y=q.y;}else{clampTankXZ(t,e.pos,e.surf?.t==='air'?.5:1.2);e.pos.y=clamp(e.pos.y,-1,TH-2);}}}

// Offscreen tanks run as coarse ecosystem ticks instead of 60 full updates/second.
const _updTank15=updTank;
updTank=function(t,dt){if(!t||t.owned===false)return;return withTankDims(t,()=>{if(t.id!==G.cur){t._bgAccum=(t._bgAccum||0)+dt;if(t._bgAccum<.35)return;dt=Math.min(.55,t._bgAccum);t._bgAccum=0;}const r=_updTank15(t,dt);enforceTankBounds15(t);return r;});};

const PRESET_DEF15={
 corkForest:{name:'Cork Forest',sub:'coco',cost:58,style:'wood',density:10},flowerGarden:{name:'Flower Garden',sub:'mossbed',cost:62,style:'flower',density:11},oldForest:{name:'Old Forest Floor',sub:'coco',cost:54,style:'ground',density:12},spiderParadise:{name:'Spider Paradise',sub:'mossbed',cost:78,style:'balanced',density:13},overgrownRuin:{name:'Overgrown Ruin',sub:'coco',cost:74,style:'ruin',density:12},
 canopyTower:{name:'Canopy Tower',sub:'coco',cost:72,style:'vertical',density:11},verticalHunter:{name:'Vertical Hunter',sub:'coco',cost:66,style:'verticalWood',density:9},bromeliadWall:{name:'Bromeliad Wall',sub:'mossbed',cost:70,style:'foliage',density:11},vineColumn:{name:'Vine Column',sub:'coco',cost:64,style:'vine',density:10},rainforest:{name:'Rainforest Canopy',sub:'mossbed',cost:82,style:'rainforest',density:14},
 dryWoodland:{name:'Dry Woodland',sub:'clay',cost:56,style:'dry',density:10},rockyCanyon:{name:'Rocky Canyon',sub:'gravel',cost:68,style:'rock',density:11},meadowRun:{name:'Meadow Run',sub:'coco',cost:62,style:'meadow',density:12},longHunt:{name:'Long Hunt Lane',sub:'sand',cost:54,style:'lane',density:9},flowerVerge:{name:'Flower Verge',sub:'mossbed',cost:65,style:'flower',density:12},
 slingNursery:{name:'Sling Nursery',sub:'coco',cost:28,style:'nursery',density:6},minimalBreeder:{name:'Minimal Breeder',sub:'coco',cost:22,style:'breeder',density:4},mossCup:{name:'Moss Cup',sub:'mossbed',cost:30,style:'moss',density:6},tinyJungle:{name:'Tiny Jungle',sub:'mossbed',cost:36,style:'foliage',density:7},
 deepJungle:{name:'Deep Jungle',sub:'mossbed',cost:88,style:'rainforest',density:15},rootCathedral:{name:'Root Cathedral',sub:'coco',cost:84,style:'root',density:12},layeredRock:{name:'Layered Rock',sub:'gravel',cost:76,style:'rock',density:13},mushroomGrove:{name:'Mushroom Grove',sub:'mossbed',cost:70,style:'mushroom',density:12},cubeParadise:{name:'Cube Paradise',sub:'mossbed',cost:92,style:'balanced',density:16},
 cleanBreeder:{name:'Clean Breeder',sub:'coco',cost:24,style:'breeder',density:4},corkStrip:{name:'Cork Strip',sub:'coco',cost:32,style:'verticalWood',density:5},feedingLedge:{name:'Feeding Ledge Setup',sub:'coco',cost:30,style:'utility',density:5},dryMinimal:{name:'Dry Minimal',sub:'sand',cost:26,style:'dry',density:5},
 woodlandPanorama:{name:'Woodland Panorama',sub:'coco',cost:96,style:'wood',density:16},gardenWalk:{name:'Garden Walk',sub:'mossbed',cost:98,style:'flower',density:17},canyonRun:{name:'Canyon Run',sub:'gravel',cost:94,style:'rock',density:16},showcaseJungle:{name:'Showcase Jungle',sub:'mossbed',cost:112,style:'rainforest',density:19},panoramicRuin:{name:'Panoramic Ruin',sub:'coco',cost:108,style:'ruin',density:17},
 jarJungle:{name:'Jar Jungle',sub:'mossbed',cost:62,style:'foliage',density:9},mossLantern:{name:'Moss Lantern',sub:'mossbed',cost:58,style:'mushroom',density:8},vineSpiral:{name:'Vine Spiral',sub:'coco',cost:64,style:'vine',density:9},flowerJar:{name:'Flower Jar',sub:'mossbed',cost:60,style:'flower',density:9},verticalJar:{name:'Vertical Cork Jar',sub:'coco',cost:58,style:'verticalWood',density:8}
};
function decorPool15(t,style){const ids=Object.keys(DECOR).filter(id=>tankAllowsDecor(t,id));const wanted={
 wood:['wood','ground','foliage'],flower:['flower','foliage','ground'],ground:['ground','wood','small'],balanced:['wood','foliage','flower','ground','utility'],ruin:['rock','foliage','ground','cozy'],vertical:['vertical','foliage','wood'],verticalWood:['vertical','wood','utility'],foliage:['foliage','ground'],vine:['vertical','foliage'],rainforest:['foliage','vertical','wood','ground'],dry:['wood','rock','ground'],rock:['rock','ground','wood'],meadow:['flower','foliage','ground'],lane:['ground','small','utility'],nursery:['small','foliage','utility','breeder'],breeder:['breeder','utility','small','ground'],moss:['ground','foliage','small'],root:['wood','vertical','foliage'],mushroom:['foliage','ground','cozy'],utility:['utility','wood','small']
 }[style]||['ground','wood'];return ids.filter(id=>(DECOR[id].groups||[]).some(g=>wanted.includes(g)));}
function clearDecor15(t,refund=false){if(refund)for(const d of t.decor)G.coins+=Math.floor((DECOR[d.type]?.price||0)/2);t.decor=[];t.bgKey='';t.bg=null;t.stat=null;for(const e of [...t.spiders,...t.prey]){e.surf=S_FLOOR;e.pos.y=0;e.route=null;e.jump=null;if(e.kind==='spider'){e.hunt=null;e.retreat=null;}}t.silk=[];t.drops=[];}
function applyPreset15(t,id,free=false,rollInc=false){const P=PRESET_DEF15[id];if(!P)return;if(!free&&G.coins<P.cost)return toast('Not enough coins');if(!free)G.coins-=P.cost;if(rollInc)t.presetRoll=(t.presetRoll||0)+1;clearDecor15(t,false);t.sub=P.sub;t.lastPreset=id;const seed=((t.id+1)*73856093+(t.presetRoll||0)*19349663+[...id].reduce((a,c)=>a+c.charCodeAt(0),0)*83492791)>>>0,R=rng(seed),pool=decorPool15(t,P.style),T=tankType(t);let n=Math.max(3,Math.round(P.density*Math.sqrt((T.w*T.d)/(200*90))));if(t.tankType==='nano'||t.tankType==='acrylic')n=Math.min(n,P.density);if(t.tankType==='panoramic')n=Math.max(n,P.density+2);
 // Give vertical habitats a deliberate tall anchor first.
 const anchors=P.style.includes('vertical')||P.style==='rainforest'||P.style==='vine';if(anchors){const cand=['mosspole','corktube','tower','vine','palm','forkbranch'].filter(x=>pool.includes(x));if(cand.length){const id0=pick(cand),q=fitDecorPos15(t,id0,T.w*(.18+R()*.18),T.d*(.28+R()*.25),0);if(canPlaceDecor15(t,id0,q.x,q.z,0))addDecor(t,id0,q.x,q.z,0,(R()*1e9)|0);}}
 let tries=0;while(t.decor.length<n&&tries<n*35){tries++;if(!pool.length)break;let id2=pool[Math.floor(R()*pool.length)],rot=R()>.72?1:0;const D=DECOR[id2],edge=P.style==='lane'&&R()<.72,x=edge?(R()<.5?T.w*.12:T.w*.88):T.w*(.08+R()*.84),z=T.d*(.08+R()*.84),q=fitDecorPos15(t,id2,x,z,rot);if(canPlaceDecor15(t,id2,q.x,q.z,rot))addDecor(t,id2,q.x,q.z,rot,(R()*1e9)|0);}
 for(const e of [...t.spiders,...t.prey]){clampTankXZ(t,e.pos,2);const g=groundAt(t,e.pos.x,e.pos.z);e.surf=g.p?{t:'plat',id:g.p.id}:S_FLOOR;e.pos.y=g.h;e.route=null;if(e.kind==='spider')e.hunt=null;}clearTankCaches15(t);SFX.place();toast(`${P.name} applied to ${t.name}`);}
function saveCustomPreset15(t){const name=prompt('Name this habitat layout:',`${t.name} layout`);if(!name)return;G.customPresets=G.customPresets||[];const T=tankType(t);G.customPresets.push({id:'c'+Date.now(),name:name.slice(0,40),source:t.tankType,sub:t.sub,decor:t.decor.map(d=>({type:d.type,nx:d.x/T.w,nz:d.z/T.d,rot:d.rot,seed:d.seed}))});if(G.customPresets.length>20)G.customPresets.shift();save();toast(`Saved “${name.slice(0,40)}” to My Presets`);openDrawer('presets');}
function applyCustomPreset15(t,p){const T=tankType(t),items=p.decor.filter(d=>DECOR[d.type]&&tankAllowsDecor(t,d.type)),cost=Math.max(0,Math.round(items.reduce((a,d)=>a+(DECOR[d.type].price||0),0)*.65));if(G.coins<cost)return toast(`Need 🪙 ${cost}`);G.coins-=cost;clearDecor15(t,false);t.sub=p.sub||t.sub;for(const d of items){const q=fitDecorPos15(t,d.type,d.nx*T.w,d.nz*T.d,d.rot);if(canPlaceDecor15(t,d.type,q.x,q.z,d.rot))addDecor(t,d.type,q.x,q.z,d.rot,d.seed);}clearTankCaches15(t);toast(`Applied ${p.name} • 🪙 ${cost}`);}

function changeTankType15(t,id){if(!TANK_TYPES[id]||t.tankType===id)return;const old=tankType(t),neu=TANK_TYPES[id],resident=t.spiders.filter(s=>!s.owner).length;if(resident>neu.cap){toast(`${neu.name} holds ${neu.cap} jumper${neu.cap===1?'':'s'} • move ${resident-neu.cap} jumper${resident-neu.cap===1?'':'s'} out first`);return;}const swapCost=Math.max(0,Math.round(neu.price-old.price*.5));if(G.coins<swapCost){toast(`Need 🪙 ${swapCost} to replace this enclosure`);return;}const had=t.decor.length||t.prey.length||t.spiders.length;if(!confirm(`Replace ${t.name} with a ${neu.name} for 🪙 ${swapCost}? Animals are kept, compatible decor is moved, incompatible decor is returned for full value, and old silk is removed.`))return;G.coins-=swapCost;const dec=t.decor.map(d=>({type:d.type,nx:d.x/old.w,nz:d.z/old.d,rot:d.rot,seed:d.seed}));const ents=[...t.spiders,...t.prey];t.tankType=id;withTankDims(t,()=>{const keep=[];for(const d of dec){if(!tankAllowsDecor(t,d.type)){G.coins+=DECOR[d.type]?.price||0;continue;}const q=fitDecorPos15(t,d.type,d.nx*neu.w,d.nz*neu.d,d.rot);if(canPlaceDecor15(t,d.type,q.x,q.z,d.rot)){const it=addDecor(t,d.type,q.x,q.z,d.rot,d.seed);if(it)keep.push(it);}else G.coins+=DECOR[d.type]?.price||0;}t.decor=keep;for(const e of ents){e.pos.x=e.pos.x/old.w*neu.w;e.pos.z=e.pos.z/old.d*neu.d;e.pos.y=0;clampTankXZ(t,e.pos,2);e.surf=S_FLOOR;e.route=null;e.jump=null;if(e.kind==='spider'){e.hunt=null;e.retreat=null;}}t.silk=[];t.drops=[];t.husks=[];clearTankCaches15(t);});if(G.cur===t.id){setTankDims(t);setCam(cam.mode);}if(UI.drawer)closeDrawer();renderTabs();renderHabitats15();save();toast(`${t.name} is now a ${neu.name}`);}
function buySlot15(i,type){const t=G.tanks[i],base=SLOT_PRICE15[i]||0,extra=TANK_TYPES[type].price,total=base+extra;if(G.coins<total)return toast(`Need 🪙 ${total}`);G.coins-=total;t.owned=true;t.tankType=type;t.name=`Habitat ${i+1}`;clearTankCaches15(t);switchTank15(i);save();toast(`New ${TANK_TYPES[type].name} ready!`);}
function switchTank15(i){const t=G.tanks[i];if(!t||!t.owned)return;if(UI.drawer)closeDrawer();G.cur=i;G.sel=null;setTankDims(t);setCam(cam.mode);VIEW.z=1;clampView();renderTabs();closeModal('habModal15');SFX.click();}

function ensureHabitatUI15(){if($('habBtn15'))return;const b=document.createElement('button');b.id='habBtn15';b.textContent='🏠 Habitats';b.onclick=()=>{SFX.click();renderHabitats15();$('habModal15').style.display='flex';};$('tabs').after(b);
 const st=document.createElement('style');st.textContent=`#habgrid15{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}.hab15{background:linear-gradient(#efdcb4,#d8bc89);border:1px solid #8a5a35;border-radius:7px;padding:9px}.hab15.active{outline:3px solid #3f7a2a}.hab15.locked{filter:saturate(.72);opacity:.88}.hab15 h3{margin:0 0 4px}.hab15 .meta{font-size:12px;color:#6b4b30;margin:3px 0 7px}.hab15 select{max-width:100%;margin:4px 0}.hab15 .actions{display:flex;gap:5px;flex-wrap:wrap}.hab15 .actions button{font-size:12px;padding:4px 7px}#habSummary15{margin:0 0 10px;color:#65452a;font-style:italic}`;document.head.appendChild(st);
 const m=document.createElement('div');m.className='modal';m.id='habModal15';m.innerHTML=`<div class="panel" style="max-width:1050px"><div style="display:flex;justify-content:space-between;align-items:center"><h2>🏠 Habitat Shelf</h2><button onclick="closeModal('habModal15')">Close</button></div><p id="habSummary15"></p><div id="habgrid15"></div></div>`;document.body.appendChild(m);
 if(!$('presetBtn15')){const p=document.createElement('button');p.id='presetBtn15';p.dataset.d='presets';p.textContent='🏡 Presets';const col=$('colBtn');col.parentNode.insertBefore(p,col);p.onclick=()=>{SFX.click();openDrawer('presets');};}
}
function habitatPreview15(t){const c=document.createElement('canvas');c.width=380;c.height=116;c.style.width='100%';c.style.height='58px';c.style.borderRadius='5px';c.style.margin='4px 0 6px';const x=c.getContext('2d'),T=tankType(t),sub=SUBS[t.sub]?.c?.[0]||'#7a5a3a';x.fillStyle='#2b1c12';x.fillRect(0,0,c.width,c.height);x.save();x.translate(12,8);const w=356,h=96;x.fillStyle=sub;x.globalAlpha=.82;if(T.shape==='round'){x.beginPath();x.ellipse(w/2,h*.68,w*.42,h*.22,0,0,6.283);x.fill();x.strokeStyle='rgba(220,240,245,.7)';x.lineWidth=3;x.beginPath();x.ellipse(w/2,h*.22,w*.42,h*.18,0,0,6.283);x.stroke();x.beginPath();x.ellipse(w/2,h*.68,w*.42,h*.22,0,0,6.283);x.stroke();x.beginPath();x.moveTo(w*.08,h*.22);x.lineTo(w*.08,h*.68);x.moveTo(w*.92,h*.22);x.lineTo(w*.92,h*.68);x.stroke();}else{x.fillRect(8,h*.67,w-16,h*.22);x.strokeStyle='rgba(220,240,245,.65)';x.lineWidth=3;x.strokeRect(8,4,w-16,h*.86);}x.globalAlpha=1;for(const d of t.decor.slice(0,28)){const D=DECOR[d.type],px=8+d.x/T.w*(w-16),py=h*.66-(D.h||D.ph||3)/T.h*h*.42;x.fillStyle=D.cat==='plants'?'#6da04e':D.kind==='flat'?'#a07b4f':'#806044';x.beginPath();x.arc(px,py,Math.max(2,Math.min(7,3+(D.w||10)/18)),0,6.283);x.fill();}for(const sp of t.spiders.filter(s=>!s.owner)){const px=8+sp.pos.x/T.w*(w-16),py=h*.66-sp.pos.y/T.h*h*.5;x.fillStyle='#f4efe5';x.beginPath();x.arc(px,py,4,0,6.283);x.fill();x.fillStyle='#222';x.beginPath();x.arc(px,py,2,0,6.283);x.fill();}x.restore();return c;}
function renderHabitats15(){ensureHabitatUI15();const g=$('habgrid15');g.innerHTML='';const owned=G.tanks.filter(t=>t.owned).length;$('habSummary15').textContent=`${owned}/8 habitats active • only the habitat you are watching runs at full simulation rate; the others continue on lightweight background ticks.`;G.tanks.forEach((t,i)=>{const T=tankType(t),c=document.createElement('div');c.className='hab15'+(i===G.cur?' active':'')+(t.owned?'':' locked');if(t.owned){const lead=t.spiders.find(s=>!s.owner),status=lead?(lead.mood||lead.state||'exploring'):'Empty habitat';c.innerHTML=`<h3>${T.icon} ${t.name}</h3><div class="meta">${T.name} • ${T.w}×${T.d}×${T.h} • capacity ${T.cap}<br>🕷 ${t.spiders.length}/${T.cap} • prey ${t.prey.length} • decor ${t.decor.length} • 💧 ${Math.round((t.humidity??.38)*100)}%<br>${lead?'• '+status:'• ready for a jumper'}</div>`;c.insertBefore(habitatPreview15(t),c.querySelector('.meta'));const actions=document.createElement('div');actions.className='actions';const sw=document.createElement('button');sw.textContent=i===G.cur?'Viewing':'View';sw.disabled=i===G.cur;sw.onclick=()=>switchTank15(i);const rn=document.createElement('button');rn.textContent='Rename';rn.onclick=()=>{const n=prompt('Habitat name:',t.name);if(n){t.name=n.slice(0,28);renderTabs();renderHabitats15();save();}};const sel=document.createElement('select');for(const [id,q] of Object.entries(TANK_TYPES)){const o=document.createElement('option');o.value=id;o.textContent=`${q.icon} ${q.name}${q.price?` (🪙${q.price})`:''}`;o.selected=id===t.tankType;sel.appendChild(o);}const ch=document.createElement('button');const syncCh=()=>{const q=TANK_TYPES[sel.value],cost=Math.max(0,Math.round(q.price-T.price*.5));ch.textContent=sel.value===t.tankType?'Current enclosure':`Replace • 🪙 ${cost}`;ch.disabled=sel.value===t.tankType;};sel.onchange=syncCh;ch.onclick=()=>changeTankType15(t,sel.value);syncCh();actions.append(sw,rn,sel,ch);c.appendChild(actions);}else{const def=i===3?'nano':i===4?'arboreal':i===5?'cube':i===6?'jar':'panoramic';c.innerHTML=`<h3>🔒 Habitat Slot ${i+1}</h3><div class="meta">Shelf slot 🪙 ${SLOT_PRICE15[i]} + enclosure cost</div>`;const sel=document.createElement('select');for(const [id,q] of Object.entries(TANK_TYPES)){const o=document.createElement('option');o.value=id;o.textContent=`${q.icon} ${q.name} • 🪙 ${q.price}`;o.selected=id===def;sel.appendChild(o);}const buy=document.createElement('button');const sync=()=>buy.textContent=`Buy • 🪙 ${(SLOT_PRICE15[i]||0)+TANK_TYPES[sel.value].price}`;sel.onchange=sync;buy.onclick=()=>buySlot15(i,sel.value);sync();c.append(sel,buy);}g.appendChild(c);});}
const _renderTabs15=renderTabs;
renderTabs=function(){ensureHabitatUI15();const el=$('tabs');el.innerHTML='';for(const t of G.tanks){if(!t.owned)continue;const T=tankType(t),b=document.createElement('button');b.textContent=`${T.icon} ${t.name} (${t.spiders.length}🕷)`;b.className=t.id===G.cur?'on':'';b.onclick=()=>switchTank15(t.id);el.appendChild(b);}if($('habBtn15'))$('habBtn15').classList.toggle('on',false);};

const _openDrawer15=openDrawer;
openDrawer=function(kind){if(kind!=='decor'&&kind!=='plants'&&kind!=='presets')return _openDrawer15(kind);if(UI.drawer===kind){closeDrawer();return;}UI.drawer=kind;cancelPlace();const dr=$('drawer');dr.innerHTML='';dr.style.display='block';document.querySelectorAll('#bar button').forEach(b=>b.classList.toggle('on',b.dataset.d===kind));setTimeout(resize,0);const add=(icon,title,price,on)=>{const c=document.createElement('div');c.className='card';c.appendChild(icon);const a=document.createElement('div');a.textContent=title;const p=document.createElement('div');p.className='pr';p.textContent=price;c.append(a,p);c.onclick=()=>{document.querySelectorAll('.card').forEach(x=>x.classList.remove('sel'));c.classList.add('sel');on();};dr.appendChild(c);};const t=cur();if(kind==='decor'||kind==='plants'){for(const id in DECOR){const D=DECOR[id];if(D.cat!==kind||!tankAllowsDecor(t,id))continue;add(decorIcon(id),D.name,D.price?`🪙 ${D.price}`:'free',()=>startPlace({kind:'decor',id}));}add(iconCanvas(()=>{}),'🗑 Clear all decor','refund 50%',()=>{if(confirm('Remove all decor from this habitat?')){clearDecor15(t,true);toast('Decor cleared');}});return;}
 const T=tankType(t);for(const id of T.presets){const P=PRESET_DEF15[id];add(iconCanvas(()=>{}),P.name,`🪙 ${P.cost}`,()=>applyPreset15(t,id,false,true));}if(t.lastPreset&&PRESET_DEF15[t.lastPreset])add(iconCanvas(()=>{}),'↻ Regenerate layout','free',()=>applyPreset15(t,t.lastPreset,true,true));add(iconCanvas(()=>{}),'💾 Save current layout','My Presets',()=>saveCustomPreset15(t));for(const p of G.customPresets||[]){const compatible=p.decor.some(d=>DECOR[d.type]&&tankAllowsDecor(t,d.type));if(!compatible)continue;const cost=Math.round(p.decor.filter(d=>DECOR[d.type]&&tankAllowsDecor(t,d.type)).reduce((a,d)=>a+(DECOR[d.type].price||0),0)*.65);add(iconCanvas(()=>{}),`★ ${p.name}`,`🪙 ${cost}`,()=>applyCustomPreset15(t,p));}};

// v15 persistence and migration. Old v14 saves load as the first owned habitats.
save=function(){try{const data={v:20,coins:G.coins,clock:G.clock,catches:G.catches,unlocked:G.unlocked,cur:G.cur,journal:G.journal||{},customPresets:G.customPresets||[],tanks:G.tanks.map(t=>({name:t.name,tankType:t.tankType,owned:t.owned,sub:t.sub,humidity:t.humidity,age:t.age,presetRoll:t.presetRoll||0,lastPreset:t.lastPreset||null,decor:t.decor.map(d=>[d.type,d.x,d.z,d.rot,d.seed]),silk:(t.silk||[]).slice(-80).map(l=>({a:l.a,b:l.b,kind:l.kind,alpha:l.alpha,age:l.age})),spiders:t.spiders.filter(s=>!s.owner).map(s=>({sp:s.sp,name:s.name,stage:s.stage,meals:s.meals,sat:s.sat,thirst:s.thirst,tr:s.tr,persona:s.persona,mem:s.mem,catches:s.catches,seed:s.seed,obsPts:s.obsPts,softT:s.softT,life:s.life||null,huntMemory:s.huntMemory||null})),prey:t.prey.filter(p=>!p.owner).map(p=>p.type),husks:t.husks.slice(-40)}))};localStorage.setItem('jumperTerrarium1',JSON.stringify(data));}catch(e){console.warn('save15',e);}};
load=function(){try{const d=JSON.parse(localStorage.getItem('jumperTerrarium1')||'null');if(!d)return false;G.coins=d.coins??400;G.clock=d.clock??480*.36;G.catches=d.catches||0;G.unlocked=d.unlocked||G.unlocked;G.journal=d.journal||{};G.customPresets=d.customPresets||[];G.tanks=[];JT6.loading=true;const src=d.tanks||[];for(let i=0;i<8;i++){const td=src[i],t=makeTank(i);if(td){t.owned=td.owned!==undefined?!!td.owned:true;t.tankType=TANK_TYPES[td.tankType]?td.tankType:'standard';t.name=td.name||`Tank ${i+1}`;t.sub=td.sub||'sand';t.humidity=td.humidity??.38;t.age=td.age||0;t.presetRoll=td.presetRoll||0;t.lastPreset=td.lastPreset||null;withTankDims(t,()=>{for(const row of td.decor||[]){const [ty,x,z,rot,seed]=row;if(DECOR[ty]&&tankAllowsDecor(t,ty)){const q=fitDecorPos15(t,ty,x,z,rot);if(canPlaceDecor15(t,ty,q.x,q.z,rot))addDecor(t,ty,q.x,q.z,rot,seed);}}t.silk=(td.silk||[]).map(l=>({a:v3(l.a.x,l.a.y,l.a.z),b:v3(l.b.x,l.b.y,l.b.z),kind:l.kind,alpha:l.alpha,age:l.age||0}));for(const sd of td.spiders||[]){if(!SPEC[sd.sp])continue;const sp=newSpider(sd.sp,t);Object.assign(sp,{name:sd.name,stage:sd.stage,meals:sd.meals,sat:sd.sat,thirst:sd.thirst??.2,tr:sd.tr||sp.tr,persona:sd.persona||sp.persona,mem:sd.mem||sp.mem,catches:sd.catches||0,seed:sd.seed,obsPts:sd.obsPts||0,softT:sd.softT||0,life:sd.life||sp.life,huntMemory:sd.huntMemory||sp.huntMemory});sp.size=spSize(sp);clampTankXZ(t,sp.pos,2);const g=groundAt(t,sp.pos.x,sp.pos.z);sp.surf=g.p?{t:'plat',id:g.p.id}:S_FLOOR;sp.pos.y=g.h;t.spiders.push(sp);}for(const ty of td.prey||[])if(PREY[ty]){const p=newPrey(ty,t);clampTankXZ(t,p.pos,2);const g=groundAt(t,p.pos.x,p.pos.z);p.surf=g.p?{t:'plat',id:g.p.id}:S_FLOOR;p.pos.y=g.h;t.prey.push(p);}if(Array.isArray(td.husks))t.husks=td.husks;});}else{t.owned=false;t.tankType='standard';t.name=`Habitat ${i+1}`;}G.tanks.push(t);}JT6.loading=false;let want=clamp(d.cur||0,0,7);if(!G.tanks[want]?.owned)want=G.tanks.findIndex(t=>t.owned);G.cur=Math.max(0,want);setTankDims(G.tanks[G.cur]);return true;}catch(e){JT6.loading=false;console.warn('load15',e);return false;}};
initNew=function(){G.tanks=[];for(let i=0;i<8;i++){const t=makeTank(i);t.owned=i<3;t.tankType=i===1?'arboreal':i===2?'wide':'standard';t.name=i===0?'Starter Terrarium':i===1?'Canopy Habitat':i===2?'Wide Habitat':`Habitat ${i+1}`;G.tanks.push(t);}G.cur=0;const t=G.tanks[0];setTankDims(t);const L=[['moss',40,60],['litter',150,65],['dish',172,24],['bark',60,30],['tower',165,42],['drift',105,58],['fern',28,20],['pinkfl',125,25],['grass',192,76],['succ',82,80],['shroom',142,82],['stone',25,76]];for(const [ty,x,z] of L)if(canPlaceDecor15(t,ty,x,z,0))addDecor(t,ty,x,z);const s=newSpider('audax',t);s.name='Bolt';t.spiders.push(s);for(let i=0;i<5;i++)t.prey.push(newPrey('fruitfly',t));t.prey.push(newPrey('housefly',t));t.prey.push(newPrey('cricket',t));for(const e of t.prey){const g=groundAt(t,e.pos.x,e.pos.z);if(g.p){e.surf={t:'plat',id:g.p.id};e.pos.y=g.h;}}G.sel=s;G.customPresets=[];};
ensureHabitatUI15();
// ================= end v15 habitat expansion =================

if(!load())initNew();for(const t of G.tanks)if(t.owned)withTankDims(t,()=>ensureFloor(t));
setCam(1);resize();renderTabs();
// title art
(()=>{const c=$('titleCv'),x=c.getContext('2d');const pb=new PB(512,384);B=pb;drawJumper({x:256,y:336,u:30,view:'front',pal:SPEC.audax.pal,pat:'audax',seed:5,as:1,raise:0.6});x.putImageData(new ImageData(new Uint8ClampedArray(pb.d.buffer),512,384),0,0);})();
$('startBtn').onclick=()=>{$('title').style.display='none';audioInit();if(SND.ctx&&SND.ctx.state==='suspended')SND.ctx.resume();resize();if(TOUCH&&innerHeight>innerWidth)toast('📱 Tip: turn your device sideways for a bigger tank view');if(!localStorage.getItem('jtHelp')){localStorage.setItem('jtHelp',1);$('helpModal').style.display='flex';}};
window.addEventListener('beforeunload',save);window.addEventListener('pagehide',()=>{if(SDFP)localStorage.removeItem('jtSdfBusy');});

