let last=performance.now(),saveT=0,uiT=0;
const PG={ema:16,lvl:0,t:0,f:0};
function perfGov(raw,dt){if(raw>250||document.hidden)return;PG.ema=PG.ema*0.93+raw*0.07;PG.t+=dt;if(PG.t>2.5){PG.t=0;if(PG.ema>(PG.lvl>=2?45:30)&&PG.lvl<3){PG.lvl++;PG.ema=16;toast(['','⚡ Smoother mode: depth blur off','⚡ Smoother mode: lighter effects, 30 fps','⚡ Max smooth mode'+(QUAL>1?' – tip: Settings → Render quality: Low':'')][PG.lvl]);}}}
const STAB8={errors:0,lastGood:performance.now()};
function frameFault8(e){STAB8.errors++;console.error('Jumper Terrarium frame recovered',e);if(STAB8.errors>=2){try{SDFG=null;SDFP=null;localStorage.setItem('jtNoSDF','1');}catch(_){} }if(STAB8.errors>=4){POST8.lost=true;GLP=null;try{localStorage.setItem('jtNoGL','1');drawFallback8();}catch(_){} }}
function tick(now){requestAnimationFrame(tick);try{if(SDFP)try{sdfInit();}catch(e){SDFP=null;SDFG=null;console.warn('3D decor init recovered',e);}const raw=now-last;const dt=Math.min(0.05,Math.max(0,raw/1000));last=now;perfGov(raw,dt);
 if(G.timeMode===0)G.clock+=dt;for(const t of G.tanks){try{updTank(t,dt);}catch(e){console.warn('tank update recovered',t.id,e);}}
 if(cam.mode===3){const t=cur();let tgt=G.sel&&t.spiders.includes(G.sel)?G.sel:t.spiders.find(x=>!x.owner);if(tgt){cam.fx=lerp(cam.fx,tgt.pos.x,Math.min(1,dt*3));cam.fy=lerp(cam.fy,tgt.pos.y,Math.min(1,dt*3));cam.fz=lerp(cam.fz,tgt.pos.z,Math.min(1,dt*3));}setupCam(cam,3);}if(PG.lvl>=2&&(PG.f++&1))return;
 drawScene(cur(),cam);compose(cur(),cam,now);const L=lightLevel();ctx.globalCompositeOperation='multiply';const r=Math.round(lerp(112,255,L)),g=Math.round(lerp(118,248,L)),b=Math.round(lerp(158,236,L));ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='lighter';const lp=cam.mode===1?P(TW*0.55,TH,TD*0.4):P(TW*0.5,TH,TD*0.5);const gr=ctx.createRadialGradient(lp[0],lp[1],5*RS,lp[0],lp[1]+60*RS,cam.k*110);const la=0.08*L;gr.addColorStop(0,`rgba(255,220,150,${la})`);gr.addColorStop(1,'rgba(255,220,150,0)');ctx.fillStyle=gr;{const rr=cam.k*110+60*RS;ctx.fillRect(lp[0]-rr,lp[1]-rr,rr*2,rr*2.4);}if(L<0.45){const t=cur();for(const d of t.decor)if(DECOR[d.type].glow){const q=P(d.x,8,d.z);const gg=ctx.createRadialGradient(q[0],q[1],1,q[0],q[1],cam.k*16);gg.addColorStop(0,`rgba(90,230,220,${0.35*(1-L)})`);gg.addColorStop(1,'rgba(90,230,220,0)');ctx.fillStyle=gg;ctx.fillRect(q[0]-cam.k*16,q[1]-cam.k*16,cam.k*32,cam.k*32);}}ctx.globalCompositeOperation='source-over';if(PG.lvl<2)motes(ctx,cam,now,L);post(cur(),cam,now,L);
 const t=cur();const hasTx=t.fx.some(f=>f.type==='text');if(hasTx||UI._ovDirty){UI._ovDirty=hasTx;octx.setTransform(1,0,0,1,0,0);octx.clearRect(0,0,W,H);}if(hasTx){octx.setTransform(VIEW.z,0,0,VIEW.z,W/2-VIEW.cx*VIEW.z,H/2-VIEW.cy*VIEW.z);octx.font=`bold italic ${Math.round(11*RS)}px Georgia,serif`;octx.textAlign='center';octx.lineJoin='round';for(const f of t.fx)if(f.type==='text'){const q=Pv(f.pos);const a=Math.max(0,1-f.t/1.6);const yy=q[1]-f.t*10*RS;octx.lineWidth=3*RS;octx.strokeStyle=`rgba(40,22,8,${a*0.85})`;octx.strokeText(f.text,q[0],yy);octx.fillStyle=f.text[0]==='+'?`rgba(255,214,102,${a})`:`rgba(255,248,230,${a})`;octx.shadowColor=`rgba(255,200,90,${a*0.7})`;octx.shadowBlur=8*RS;octx.fillText(f.text,q[0],yy);octx.shadowBlur=0;}}
 uiT+=dt;if(uiT>0.2){uiT=0;$('coins').textContent=`🪙 ${G.coins}`;const td=tod();const hh=Math.floor(td*24),mm=Math.floor((td*24-hh)*60/10)*10;$('clock').textContent=`${isNight()?'🌙':'☀'} Day ${Math.floor(G.clock/DAYLEN)+1}  ${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`;renderInfo();if(UI._tabsN!==G.tanks.map(t=>t.spiders.length).join()){UI._tabsN=G.tanks.map(t=>t.spiders.length).join();renderTabs();}}saveT+=dt;if(saveT>8){saveT=0;save();}STAB8.errors=0;STAB8.lastGood=now;
 }catch(e){frameFault8(e);try{drawFallback8();}catch(_){}}}
// ================= v8 stability / freeze recovery patch =================
